"use client";
import {useCallback,useEffect,useState} from 'react';
import type {Locale} from '@/lib/i18n';
import {getTjaiFlowCopy} from '@/lib/tjai/flow-copy';
import {turkeyPeriod} from '@/lib/tjai/intake-validation';
import {strengthTrends} from '@/lib/progress/strength-trends';
type SetRow={reps:number;weight_kg:number};
type BodyRow={id:string;entry_date:string;weight_kg:number|null};
type Workout={id:string;workout_date:string;exercise:string;sets:number|null;reps:number|null;weight_kg:number|null;sets_data:SetRow[]|null};
type Meal={id:string;entry_date:string;name:string;calories:number;protein_g:number;carbs_g:number;fat_g:number;source:string};
const labels={
 en:['Training & nutrition log','Bodyweight','Workout','Nutrition','Date','Weight (kg)','Exercise','Reps','Load (kg)','Add set','Save','Edit','Delete','Cancel','Meal name','Calories','Protein (g)','Carbs (g)','Fat (g)','Estimated from plan','Log planned meal','Today’s logged total','No entries yet','Set','Recent history','Daily target','Food values are estimates. Adjust portions and labels to what you actually ate.','Workout days logged','Bodyweight change','More'],
 tr:['Antrenman ve beslenme günlüğü','Vücut ağırlığı','Antrenman','Beslenme','Tarih','Kilo (kg)','Hareket','Tekrar','Yük (kg)','Set ekle','Kaydet','Düzenle','Sil','İptal','Öğün adı','Kalori','Protein (g)','Karbonhidrat (g)','Yağ (g)','Plandan tahmini','Planlı öğünü kaydet','Bugün kaydedilen toplam','Henüz kayıt yok','Set','Son kayıtlar','Günlük hedef','Besin değerleri tahminidir. Porsiyonları ve etiketleri gerçekten yediğine göre düzenle.','Antrenman yapılan gün','Kilo değişimi','Daha fazla'],
 ar:['سجل التدريب والتغذية','وزن الجسم','التمرين','التغذية','التاريخ','الوزن (كغ)','التمرين','التكرارات','الحمل (كغ)','أضف مجموعة','احفظ','تعديل','حذف','إلغاء','اسم الوجبة','السعرات','البروتين (غ)','الكربوهيدرات (غ)','الدهون (غ)','تقديري من الخطة','سجل وجبة الخطة','إجمالي اليوم المسجل','لا توجد سجلات بعد','المجموعة','السجل الأخير','الهدف اليومي','القيم الغذائية تقديرية. عدّل الحصص والملصقات لما أكلته فعلاً.','أيام التمرين المسجلة','تغير الوزن','المزيد'],
 es:['Registro de entrenamiento y nutrición','Peso corporal','Entrenamiento','Nutrición','Fecha','Peso (kg)','Ejercicio','Repeticiones','Carga (kg)','Añadir serie','Guardar','Editar','Eliminar','Cancelar','Nombre de comida','Calorías','Proteína (g)','Carbohidratos (g)','Grasa (g)','Estimado del plan','Registrar comida planificada','Total registrado hoy','Sin registros todavía','Serie','Historial reciente','Objetivo diario','Valores estimados. Ajusta las porciones y etiquetas a lo que realmente comiste.','Días de entrenamiento registrados','Cambio de peso','Más'],
 fr:['Journal entraînement et nutrition','Poids corporel','Entraînement','Nutrition','Date','Poids (kg)','Exercice','Répétitions','Charge (kg)','Ajouter une série','Enregistrer','Modifier','Supprimer','Annuler','Nom du repas','Calories','Protéines (g)','Glucides (g)','Lipides (g)','Estimation du plan','Enregistrer le repas prévu','Total enregistré aujourd’hui','Aucune entrée','Série','Historique récent','Objectif quotidien','Valeurs estimées. Ajustez les portions et les étiquettes à ce que vous avez réellement mangé.','Jours d’entraînement enregistrés','Variation du poids','Plus']
};
const input='w-full rounded-lg border border-divider bg-black/20 px-3 py-2 text-white';
const btn='rounded-lg bg-accent px-4 py-2 font-semibold text-white disabled:opacity-40';
const trendCopy={
 en:['Logged load trends','First logged day','Latest logged day','Change','Highest recorded load on each day; repetitions are shown alongside it. Two logged days are needed to compare.'],
 tr:['Kaydedilen yük değişimi','İlk kayıt günü','Son kayıt günü','Değişim','Her gün kaydedilen en yüksek yük ve yanındaki tekrar sayısı. Karşılaştırma için iki kayıt günü gerekir.'],
 ar:['تطور الأحمال المسجلة','أول يوم مسجل','آخر يوم مسجل','التغير','أعلى حمل مسجل في كل يوم مع عدد التكرارات. تحتاج المقارنة إلى يومين مسجلين.'],
 es:['Evolución de cargas registradas','Primer día registrado','Último día registrado','Cambio','Mayor carga registrada cada día, con sus repeticiones. La comparación requiere dos días registrados.'],
 fr:['Évolution des charges enregistrées','Premier jour enregistré','Dernier jour enregistré','Variation','Charge maximale enregistrée chaque jour, avec ses répétitions. Deux jours enregistrés sont nécessaires pour comparer.']
};
export function TjaiLoggingPanel({locale}:{locale:Locale}){
 const l=labels[locale],flow=getTjaiFlowCopy(locale),today=turkeyPeriod();
 const [tab,setTab]=useState<'body'|'workout'|'nutrition'>('body'),[date,setDate]=useState(today),[editId,setEditId]=useState<string|null>(null);
 const [body,setBody]=useState<BodyRow[]>([]),[workouts,setWorkouts]=useState<Workout[]>([]),[meals,setMeals]=useState<Meal[]>([]);
 const [weight,setWeight]=useState(''),[exercise,setExercise]=useState(''),[sets,setSets]=useState<SetRow[]>([{reps:10,weight_kg:0}]);
 const [name,setName]=useState(''),[macro,setMacro]=useState({calories:'',protein_g:'',carbs_g:'',fat_g:''});
 const [plan,setPlan]=useState<any>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[show,setShow]=useState(10),[loaded,setLoaded]=useState(false);
 const refresh=useCallback(async()=>{
  setError('');
  try{
   const results=await Promise.all(['/api/progress/entries','/api/progress/workouts','/api/progress/nutrition','/api/tjai/save'].map(url=>fetch(url,{cache:'no-store'})));
   if(results.some(r=>!r.ok))throw new Error('load');
   const [b,w,n,p]=await Promise.all(results.map(r=>r.json()));setBody(b.entries);setWorkouts(w.workouts);setMeals(n.meals);setPlan(p.plan);setLoaded(true);
  }catch{setError(flow.error);}finally{setLoading(false);}
 },[flow.error]);
 useEffect(()=>{void refresh();},[refresh]);
 const reset=()=>{setEditId(null);setDate(today);setWeight('');setExercise('');setSets([{reps:10,weight_kg:0}]);setName('');setMacro({calories:'',protein_g:'',carbs_g:'',fat_g:''});};
 const send=async(url:string,payload:unknown,method='POST')=>{
  setBusy(true);setError('');setNotice('');
  try{const response=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('save');setNotice(flow.savedAt);reset();await refresh();}
  catch{setError(flow.error);}finally{setBusy(false);}
 };
 const save=()=>tab==='body'?send('/api/progress/entries',{id:editId,entry_date:date,weight_kg:weight},editId?'PATCH':'POST'):tab==='workout'?send('/api/progress/workouts',{id:editId,workout_date:date,exercise,sets_data:sets},editId?'PATCH':'POST'):send('/api/progress/nutrition',{id:editId,entry_date:date,name,...macro},editId?'PATCH':'POST');
 const remove=async(kind:string,id:string)=>{setBusy(true);setError('');try{const r=await fetch('/api/progress/'+kind+'?id='+id,{method:'DELETE'});if(!r.ok)throw new Error('delete');await refresh();}catch{setError(flow.error);}finally{setBusy(false);}};
 const totals=meals.filter(m=>m.entry_date===date).reduce((s,m)=>({calories:s.calories+Number(m.calories),protein_g:s.protein_g+Number(m.protein_g),carbs_g:s.carbs_g+Number(m.carbs_g),fat_g:s.fat_g+Number(m.fat_g)}),{calories:0,protein_g:0,carbs_g:0,fat_g:0});
 const planned=plan?.plan_json?.diet?.weeks?.[0]?.days?.[0]?.meals??[],plannedExercises=plan?.plan_json?.program?.weeks?.[0]?.days?.flatMap((d:any)=>d.exercises.map((e:any)=>e.name))??[];
 const weights=body.filter(b=>b.weight_kg!=null),change=weights.length>1?Number(weights[0].weight_kg)-Number(weights[weights.length-1].weight_kg):null;
 const trends=strengthTrends(workouts),tc=trendCopy[locale],hasMeals=meals.some(m=>m.entry_date===date);
 const field=(label:string,value:string,onChange:(s:string)=>void,type='number')=><label className="block space-y-1 text-sm"><span>{label}</span><input required type={type} min={type==='number'?0:undefined} step={type==='number'?'any':undefined} value={value} onChange={e=>onChange(e.target.value)} className={input}/></label>;
 return <section dir={locale==='ar'?'rtl':'ltr'} className="space-y-6">
 <h2 className="text-2xl font-bold text-white">{l[0]}</h2>
 <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-divider p-4"><p className="text-sm text-muted">{l[27]}</p><p className="text-3xl">{loaded?new Set(workouts.map(w=>w.workout_date)).size:'—'}</p></div><div className="rounded-xl border border-divider p-4"><p className="text-sm text-muted">{l[28]}</p><p className="text-3xl">{change===null?'—':(change>0?'+':'')+change.toFixed(1)+' kg'}</p></div></div>
 <div className="flex flex-wrap gap-2" role="tablist">{(['body','workout','nutrition'] as const).map((key,i)=><button key={key} disabled={busy} role="tab" aria-selected={tab===key} className={tab===key?btn:'rounded-lg border border-divider px-4 py-2'} onClick={()=>{setTab(key);reset();setShow(10);}}>{l[i+1]}</button>)}</div>
 {error&&<p role="alert" className="text-amber-300">{error} <button className="underline" onClick={()=>void refresh()}>{flow.retry}</button></p>}{notice&&<p role="status" className="text-emerald-300">{notice}</p>}
 {loading?<p role="status">{flow.loading}</p>:<><form onSubmit={e=>{e.preventDefault();void save();}} className="rounded-2xl border border-divider bg-card p-5"><fieldset disabled={busy} className="space-y-4">
 {field(l[4],date,setDate,'date')}
 {tab==='body'&&field(l[5],weight,setWeight)}
 {tab==='workout'&&<>{field(l[6],exercise,setExercise,'text')}{plannedExercises.length>0&&<select aria-label={l[6]} className={input} value="" onChange={e=>setExercise(e.target.value)}><option value="">{l[6]}</option>{Array.from(new Set<string>(plannedExercises)).map(n=><option key={n}>{n}</option>)}</select>}
 <div className="space-y-2">{sets.map((s,i)=><div className="grid grid-cols-[2rem_1fr_1fr_2rem] items-end gap-2" key={i}><span>{i+1}</span><label className="text-sm">{l[7]}<input className={input} type="number" required min="1" max="1000" value={s.reps} onChange={e=>setSets(rows=>rows.map((r,j)=>j===i?{...r,reps:Number(e.target.value)}:r))}/></label><label className="text-sm">{l[8]}<input className={input} type="number" required min="0" max="2000" step="0.25" value={s.weight_kg} onChange={e=>setSets(rows=>rows.map((r,j)=>j===i?{...r,weight_kg:Number(e.target.value)}:r))}/></label><button type="button" aria-label={l[12]+' '+l[23]+' '+(i+1)} disabled={sets.length===1} onClick={()=>setSets(rows=>rows.filter((_,j)=>i!==j))}>×</button></div>)}</div><button type="button" className="text-accent" disabled={sets.length>=30} onClick={()=>setSets(rows=>[...rows,{...rows[rows.length-1]}])}>+ {l[9]}</button></>}
 {tab==='nutrition'&&<>{field(l[14],name,setName,'text')}<div className="grid grid-cols-2 gap-3">{(['calories','protein_g','carbs_g','fat_g'] as const).map((key,i)=><div key={key}>{field(l[15+i],macro[key],v=>setMacro(m=>({...m,[key]:v})))}</div>)}</div><p className="text-xs text-muted">{l[26]}</p></>}
 <div className="flex gap-4"><button disabled={busy} className={btn}>{busy?flow.loading:l[10]}</button>{editId&&<button type="button" onClick={reset}>{l[13]}</button>}</div></fieldset></form>
 {tab==='nutrition'&&<div className="space-y-4 rounded-2xl border border-divider p-5"><h3 className="font-semibold">{date===today?l[21]:date}</h3><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{(['calories','protein_g','carbs_g','fat_g'] as const).map((key,i)=><div key={key}><p className="text-xs text-muted">{l[15+i]}</p><p className="text-xl">{hasMeals?Math.round(totals[key]):'—'}</p><p className="text-xs text-muted">{l[25]}: {plan?.plan_json?.summary?.[['calorieTarget','protein','carbs','fat'][i]]??'—'}</p></div>)}</div>{!hasMeals&&<p className="text-sm text-muted">{l[22]}</p>}{planned.length>0&&<><p className="text-sm">{l[19]}</p><div className="flex flex-wrap gap-2">{planned.map((m:any,i:number)=><button key={i} className="rounded-lg border border-divider px-3 py-2 text-sm" disabled={busy} onClick={()=>void send('/api/progress/nutrition',{planId:plan.id,weekIndex:0,dayIndex:0,mealIndex:i,entry_date:date})}>{l[20]}: {m.name} · {m.calories} kcal</button>)}</div></>}</div>}
 {tab==='workout'&&trends.length>0&&<section className="space-y-3" aria-label={tc[0]}><h3 className="font-semibold">{tc[0]}</h3><p className="text-sm text-muted">{tc[4]} {l[24]}.</p><div className="grid gap-3 md:grid-cols-2">{trends.map(trend=><article key={trend.exercise} className="rounded-xl border border-divider p-4"><h4 className="font-semibold">{trend.exercise}</h4><dl className="mt-3 grid grid-cols-2 gap-3 text-sm">{([['first',tc[1]],['latest',tc[2]]] as const).map(([key,title])=><div key={key}><dt className="text-muted">{title}</dt><dd><span dir="ltr">{trend[key].load} kg · {trend[key].reps??'—'} {l[7]}</span><time className="block text-xs text-muted" dateTime={trend[key].date}>{trend[key].date}</time></dd></div>)}<div><dt className="text-muted">{tc[3]}</dt><dd dir="ltr">{trend.change===null?'—':(trend.change>0?'+':'')+Number(trend.change.toFixed(2))+' kg'}</dd></div></dl></article>)}</div></section>}
 <h3 className="font-semibold">{l[24]}</h3><div className="space-y-2">
 {tab==='body'&&(body.length?body.slice(0,show).map(row=><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-divider p-4" key={row.id}><span>{row.entry_date} · {row.weight_kg??'—'} kg</span><span className="flex gap-4"><button disabled={busy} onClick={()=>{setEditId(row.id);setDate(row.entry_date);setWeight(String(row.weight_kg??''));}}>{l[11]}</button><button disabled={busy} onClick={()=>void remove('entries',row.id)}>{l[12]}</button></span></div>):<p>{l[22]}</p>)}
 {tab==='workout'&&(workouts.length?workouts.slice(0,show).map(row=><div className="rounded-xl border border-divider p-4" key={row.id}><div className="flex flex-wrap justify-between gap-2"><span>{row.workout_date} · {row.exercise}</span><span className="flex gap-4"><button disabled={busy} onClick={()=>{setEditId(row.id);setDate(row.workout_date);setExercise(row.exercise);setSets(row.sets_data??Array.from({length:Math.min(30,row.sets??1)},()=>({reps:row.reps??10,weight_kg:Number(row.weight_kg??0)})));}}>{l[11]}</button><button disabled={busy} onClick={()=>void remove('workouts',row.id)}>{l[12]}</button></span></div><p className="mt-2 text-sm text-muted">{row.sets_data?row.sets_data.map((s,i)=>(i+1)+': '+s.reps+' × '+s.weight_kg+' kg').join(' · '):(row.sets??'—')+' × '+(row.reps??'—')+' · '+(row.weight_kg??'—')+' kg'}</p></div>):<p>{l[22]}</p>)}
 {tab==='nutrition'&&(meals.length?meals.slice(0,show).map(row=><div className="flex flex-wrap justify-between gap-3 rounded-xl border border-divider p-4" key={row.id}><span>{row.entry_date} · {row.name} · {row.calories} kcal {row.source==='plan_estimate'&&<small className="block text-muted">{l[19]}</small>}</span><span className="flex gap-4"><button disabled={busy} onClick={()=>{setEditId(row.id);setDate(row.entry_date);setName(row.name);setMacro({calories:String(row.calories),protein_g:String(row.protein_g),carbs_g:String(row.carbs_g),fat_g:String(row.fat_g)});}}>{l[11]}</button><button disabled={busy} onClick={()=>void remove('nutrition',row.id)}>{l[12]}</button></span></div>):<p>{l[22]}</p>)}
 </div>{show<(tab==='body'?body.length:tab==='workout'?workouts.length:meals.length)&&<button className="text-accent" onClick={()=>setShow(n=>n+20)}>{l[29]}</button>}</>}
 </section>;
}
