import { jsPDF } from "jspdf";

import type { TJAIPlan } from "@/lib/tjai-types";

export function buildTJAIPlanPdf(args: { userName: string; goal: string; generatedAt: string; plan: TJAIPlan }) {
  const { userName, goal, generatedAt, plan } = args;
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = 595;
  const margin = 40;

  const addHeader = (title: string) => {
    pdf.setDrawColor(34, 211, 238);
    pdf.setLineWidth(2);
    pdf.line(0, 20, pageWidth, 20);
    pdf.setFontSize(16);
    pdf.setTextColor(34, 211, 238);
    pdf.text("TJFit", margin, 45);
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(12);
    pdf.text(title, margin, 70);
  };

  pdf.setFillColor(9, 9, 11);
  pdf.rect(0, 0, pageWidth, 842, "F");
  addHeader("Your 12-Week Transformation Plan");
  pdf.setFontSize(28);
  pdf.setTextColor(255, 255, 255);
  pdf.text(userName || "TJFit Member", margin, 140);
  pdf.setFontSize(12);
  pdf.setTextColor(161, 161, 170);
  pdf.text(`Generated ${new Date(generatedAt).toLocaleDateString()}`, margin, 170);
  pdf.text(`Goal: ${goal}`, margin, 188);

  pdf.addPage();
  pdf.setFillColor(255, 255, 255);
  pdf.rect(0, 0, pageWidth, 842, "F");
  addHeader("Plan Summary");
  pdf.setTextColor(20, 20, 20);
  pdf.text(`Daily calories: ${plan.summary.calorieTarget} kcal`, margin, 110);
  pdf.text(`Macros: Protein ${plan.summary.protein}g / Carbs ${plan.summary.carbs}g / Fat ${plan.summary.fat}g`, margin, 130);
  pdf.text(`Water: ${plan.summary.water}ml`, margin, 150);
  pdf.text(`Time to goal: ${plan.summary.timeToGoal}`, margin, 170);
  pdf.text(plan.diet.philosophy.slice(0, 350), margin, 205, { maxWidth: 510 });

  for (const week of plan.program.weeks) {
    pdf.addPage();
    pdf.setFillColor(255, 255, 255);
    pdf.rect(0, 0, pageWidth, 842, "F");
    addHeader(`${week.weekRange} — ${week.phase}`);
    let y = 110;
    for (const day of week.days) {
      if (y > 760) break;
      pdf.setTextColor(20, 20, 20);
      pdf.setFontSize(12);
      pdf.text(`${day.day}: ${day.label}`, margin, y);
      y += 16;
      for (const ex of day.exercises.slice(0, 8)) {
        if (y > 760) break;
        pdf.setFontSize(10);
        pdf.text(`- ${ex.name} | ${ex.sets}x${ex.reps} | Rest ${ex.rest}`, margin + 10, y);
        y += 13;
      }
      y += 8;
    }
  }

  pdf.addPage();
  pdf.setFillColor(255, 255, 255);
  pdf.rect(0, 0, pageWidth, 842, "F");
  addHeader("Generated by TJAI — TJFit's AI Coach");
  pdf.setTextColor(20, 20, 20);
  pdf.setFontSize(11);
  pdf.text("For support: support@tjfit.org", margin, 120);
  pdf.text("Consult a healthcare professional before starting.", margin, 140);

  return pdf.output("arraybuffer");
}
