import Link from "next/link";

import { PremiumPageShell } from "@/components/premium";
import { programs } from "@/lib/content";
import { requireLocaleParam } from "@/lib/require-locale";

export default function PressPage({ params }: { params: { locale: string } }) {
  const locale = requireLocaleParam(params.locale);
  const programCount = programs.length;

  return (
    <PremiumPageShell className="max-w-6xl">
      <section className="rounded-2xl border border-[#1E2028] bg-[#111215] p-6 sm:p-8">
        <h1 className="text-3xl font-extrabold text-white sm:text-4xl">Press & Media</h1>
        <p className="mt-2 text-sm text-[#A1A1AA]">For press inquiries, partnership requests, and media resources.</p>
      </section>

      <section className="mt-6 rounded-2xl border border-[#1E2028] bg-[#111215] p-6">
        <h2 className="text-xl font-bold text-white">Official TJFit Assets</h2>
        <div className="mt-4 grid gap-3 sm:grid-cols-2">
          {[
            ["TJFit Logo (PNG)", "/brand/logo-main.png"],
            ["TJFit Logo Source", "/brand/logo-source.png"],
            ["TJFit Mark (PNG)", "/brand/logo-mark.png"],
            ["OG Image", "/og-image.jpg"]
          ].map(([label, href]) => (
            <a
              key={label}
              href={href}
              className="inline-flex min-h-[44px] items-center justify-between rounded-xl border border-[#1E2028] bg-[#0D1015] px-4 py-2 text-sm text-zinc-200 hover:border-white/20"
            >
              <span>{label}</span>
              <span className="text-cyan-300">Download</span>
            </a>
          ))}
        </div>
        <p className="mt-3 text-xs text-[#52525B]">Please do not alter our logo or use it in misleading ways.</p>
      </section>

      <section className="mt-6 rounded-2xl border border-[#1E2028] bg-[#111215] p-6">
        <h2 className="text-xl font-bold text-white">Brand Colors</h2>
        <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {[
            ["Primary", "#22D3EE"],
            ["Secondary", "#0EA5E9"],
            ["Background", "#09090B"],
            ["Text", "#FFFFFF"]
          ].map(([name, value]) => (
            <div key={name} className="rounded-xl border border-[#1E2028] bg-[#0D1015] p-3">
              <div className="h-10 rounded-lg border border-white/10" style={{ backgroundColor: value }} />
              <p className="mt-2 text-sm font-semibold text-white">{name}</p>
              <p className="text-xs text-[#A1A1AA]">{value}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-6 rounded-2xl border border-[#1E2028] bg-[#111215] p-6">
        <h2 className="text-xl font-bold text-white">About TJFit</h2>
        <p className="mt-3 text-sm leading-7 text-[#A1A1AA]">
          TJFit is a global AI-powered fitness platform launched in 2026. It provides personalized 12-week fitness programs and
          nutrition plans generated by TJAI, our proprietary AI fitness coach. TJFit is available in English, Turkish, Arabic,
          Spanish, and French, serving members across 50+ countries.
        </p>
        <p className="mt-3 text-sm leading-7 text-[#A1A1AA]">
          TJFit connects users with certified fitness coaches through a global marketplace, offering programs for fat loss, muscle
          building, home training, rehabilitation, and special populations including seniors, pregnancy, and children.
        </p>
      </section>

      <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <div className="rounded-xl border border-[#1E2028] bg-[#111215] p-4"><p className="text-xs text-[#52525B]">Members</p><p className="mt-1 text-xl font-bold text-white">Growing daily</p></div>
        <div className="rounded-xl border border-[#1E2028] bg-[#111215] p-4"><p className="text-xs text-[#52525B]">Languages</p><p className="mt-1 text-xl font-bold text-white">5</p></div>
        <div className="rounded-xl border border-[#1E2028] bg-[#111215] p-4"><p className="text-xs text-[#52525B]">Programs</p><p className="mt-1 text-xl font-bold text-white">{programCount}</p></div>
        <div className="rounded-xl border border-[#1E2028] bg-[#111215] p-4"><p className="text-xs text-[#52525B]">Countries reached</p><p className="mt-1 text-xl font-bold text-white">50+</p></div>
      </section>

      <section className="mt-6 rounded-2xl border border-[#1E2028] bg-[#111215] p-6">
        <h2 className="text-xl font-bold text-white">Press Contact</h2>
        <p className="mt-2 text-sm text-[#A1A1AA]">Media inquiries: press@tjfit.org</p>
        <p className="text-sm text-[#A1A1AA]">Partnerships: partners@tjfit.org</p>
        <p className="text-sm text-[#A1A1AA]">Response time: within 48 hours</p>
      </section>

      <section className="mt-6 rounded-2xl border border-[#1E2028] bg-[#111215] p-6">
        <h2 className="text-xl font-bold text-white">Recent Coverage</h2>
        <p className="mt-2 text-sm text-[#A1A1AA]">No press coverage listed yet.</p>
        <Link href={`/${locale}`} className="mt-4 inline-flex text-sm font-semibold text-cyan-300">
          Back to TJFit →
        </Link>
      </section>
    </PremiumPageShell>
  );
}
