import type {Locale} from '@/lib/i18n';
const copy={
 en:{signin:'Sign in to save your assessment',signup:'Create an account',save:'Save my assessment',temporary:'Your completed answers stay in this tab for up to two hours while you sign in. They are removed after saving.',expired:'Your answers are not available in this tab. If your verification email opened a new tab, return to the original assessment tab and sign in there. If that tab has closed or expired, complete the assessment again.'},
 tr:{signin:'Yanıtlarını kaydetmek için giriş yap',signup:'Hesap oluştur',save:'Yanıtlarımı kaydet',temporary:'Giriş yaparken tamamlanan yanıtların bu sekmede en fazla iki saat tutulur. Kaydedildikten sonra silinir.',expired:'Yanıtların bu sekmede yok. Doğrulama e-postası yeni bir sekme açtıysa ilk değerlendirme sekmesine dönüp orada giriş yap. İlk sekme kapandıysa veya süresi dolduysa değerlendirmeyi yeniden tamamla.'},
 ar:{signin:'سجّل الدخول لحفظ إجاباتك',signup:'أنشئ حساباً',save:'احفظ إجاباتي',temporary:'تبقى إجاباتك المكتملة في علامة التبويب هذه لمدة ساعتين أثناء تسجيل الدخول، ثم تُحذف بعد حفظها.',expired:'إجاباتك غير متاحة في علامة التبويب هذه. إذا فتح بريد التحقق علامة تبويب جديدة، فعد إلى علامة تبويب التقييم الأصلية وسجّل الدخول فيها. إذا أُغلقت أو انتهت مدتها، فأكمل التقييم مجدداً.'},
 es:{signin:'Inicia sesión para guardar tus respuestas',signup:'Crear una cuenta',save:'Guardar mis respuestas',temporary:'Tus respuestas completas permanecen en esta pestaña hasta dos horas mientras inicias sesión. Se eliminan después de guardarlas.',expired:'Tus respuestas no están en esta pestaña. Si el correo de verificación abrió otra pestaña, vuelve a la evaluación original e inicia sesión allí. Si esa pestaña se cerró o caducó, completa la evaluación de nuevo.'},
 fr:{signin:'Connectez-vous pour enregistrer vos réponses',signup:'Créer un compte',save:'Enregistrer mes réponses',temporary:'Vos réponses restent dans cet onglet pendant deux heures au maximum lors de la connexion. Elles sont supprimées après enregistrement.',expired:'Vos réponses ne sont pas dans cet onglet. Si le lien de vérification a ouvert un nouvel onglet, revenez au questionnaire d’origine et connectez-vous dans cet onglet. S’il a été fermé ou a expiré, recommencez le questionnaire.'}
};
export const getAssessmentCopy=(locale:Locale)=>copy[locale];
