import type {Locale} from '@/lib/i18n';
const values={
 en:{title:'Your TJAI plan',start:'Build my plan',saved:'Your plan is saved',review:'Review intake',generate:'Generate my plan',retry:'Try again',back:'View saved plan',adult:'I am 18 or older and want general fitness guidance, not medical treatment.',consent:'I agree that my fitness answers and chat messages may be processed by Groq in the US. I will not include names, contact details or medical records.',continue:'Continue to intake',queued:'Your plan is queued. You can leave this page and return; your request is saved.',failed:'Your plan could not be completed. Your allowance has not been used. Try again later.',error:'We could not load or save this information. Please try again.',adults:'TJAI is for adults aged 18–100. Check your age, height and weight.',terms:'$19.99 once · saved plans and logs · 5 successful chat replies per day · one regeneration per Türkiye calendar month. Free AI capacity can cause delays.',buy:'Continue to secure payment',payment:'Payment confirmation',pending:'Waiting for verified payment. You can return here after checkout.',paid:'Payment confirmed. Create your plan.',limit:'Your regeneration is available next Türkiye calendar month.',loading:'Loading…',savedAt:'Saved',confirm:'Confirm and continue',disabled:'This extra feature is currently unavailable.'},
 tr:{title:'TJAI planın',start:'Planımı oluştur',saved:'Planın kaydedildi',review:'Yanıtları incele',generate:'Planımı üret',retry:'Tekrar dene',back:'Kayıtlı planı gör',adult:'18 yaşındayım veya daha büyüğüm; tıbbi tedavi değil genel fitness rehberliği istiyorum.',consent:'Fitness yanıtlarımın ve sohbet mesajlarımın Groq tarafından ABD’de işlenmesini kabul ediyorum. İsim, iletişim bilgisi veya tıbbi kayıt paylaşmayacağım.',continue:'Ankete devam et',queued:'Planın sırada. Bu sayfadan ayrılıp dönebilirsin; isteğin kayıtlı.',failed:'Plan tamamlanamadı. Hakkın kullanılmadı. Daha sonra tekrar dene.',error:'Bilgiler yüklenemedi veya kaydedilemedi. Lütfen tekrar dene.',adults:'TJAI 18–100 yaş yetişkinler içindir. Yaş, boy ve kilonu kontrol et.',terms:'Tek sefer $19.99 · kayıtlı planlar ve günlükler · günde 5 başarılı sohbet yanıtı · Türkiye takvim ayı başına bir yenileme. Ücretsiz AI kapasitesi gecikmeye yol açabilir.',buy:'Güvenli ödemeye devam et',payment:'Ödeme onayı',pending:'Doğrulanmış ödeme bekleniyor. Ödeme sonrası buraya dönebilirsin.',paid:'Ödeme doğrulandı. Planını oluştur.',limit:'Plan yenileme hakkın sonraki Türkiye takvim ayında açılır.',loading:'Yükleniyor…',savedAt:'Kaydedildi',confirm:'Onayla ve devam et',disabled:'Bu ek özellik şu anda kullanılamıyor.'},
 ar:{title:'خطة TJAI الخاصة بك',start:'أنشئ خطتي',saved:'تم حفظ خطتك',review:'راجع إجاباتك',generate:'ولّد خطتي',retry:'حاول مجدداً',back:'عرض الخطة المحفوظة',adult:'عمري 18 عاماً أو أكثر وأريد إرشادات لياقة عامة وليس علاجاً طبياً.',consent:'أوافق على معالجة إجاباتي ورسائل الدردشة بواسطة Groq في الولايات المتحدة. لن أدرج أسماء أو بيانات اتصال أو سجلات طبية.',continue:'تابع إلى الاستبيان',queued:'خطتك في قائمة الانتظار. يمكنك المغادرة والعودة؛ طلبك محفوظ.',failed:'تعذر إكمال الخطة. لم يتم استهلاك رصيدك. حاول لاحقاً.',error:'تعذر تحميل أو حفظ المعلومات. حاول مجدداً.',adults:'TJAI للبالغين بين 18 و100 عام. تحقق من العمر والطول والوزن.',terms:'$19.99 مرة واحدة · خطط وسجلات محفوظة · 5 ردود ناجحة يومياً · تجديد واحد لكل شهر تقويمي في تركيا. قد تتأخر الخدمة بسبب سعة الذكاء الاصطناعي المجانية.',buy:'تابع إلى الدفع الآمن',payment:'تأكيد الدفع',pending:'ننتظر تأكيد الدفع الموثق. يمكنك العودة بعد الدفع.',paid:'تم تأكيد الدفع. أنشئ خطتك.',limit:'يتاح التجديد في الشهر التقويمي القادم بتوقيت تركيا.',loading:'جارٍ التحميل…',savedAt:'محفوظة',confirm:'أكد وتابع',disabled:'هذه الميزة الإضافية غير متاحة حالياً.'},
 es:{title:'Tu plan TJAI',start:'Crear mi plan',saved:'Tu plan está guardado',review:'Revisar respuestas',generate:'Generar mi plan',retry:'Reintentar',back:'Ver plan guardado',adult:'Tengo 18 años o más y busco orientación general de fitness, no tratamiento médico.',consent:'Acepto que Groq procese mis respuestas y mensajes en EE. UU. No incluiré nombres, datos de contacto ni historiales médicos.',continue:'Continuar al cuestionario',queued:'Tu plan está en cola. Puedes salir y volver; tu solicitud está guardada.',failed:'No se pudo completar el plan. No has gastado tu cupo. Reintenta más tarde.',error:'No se pudo cargar o guardar la información. Reinténtalo.',adults:'TJAI es para adultos de 18–100 años. Revisa edad, altura y peso.',terms:'$19.99 una vez · planes y registros guardados · 5 respuestas completas al día · una regeneración por mes de calendario de Turquía. La capacidad gratuita puede causar demoras.',buy:'Continuar al pago seguro',payment:'Confirmación de pago',pending:'Esperando el pago verificado. Puedes volver tras pagar.',paid:'Pago confirmado. Crea tu plan.',limit:'Tu regeneración estará disponible el próximo mes de calendario de Turquía.',loading:'Cargando…',savedAt:'Guardado',confirm:'Confirmar y continuar',disabled:'Esta función adicional no está disponible actualmente.'},
 fr:{title:'Votre plan TJAI',start:'Créer mon plan',saved:'Votre plan est enregistré',review:'Vérifier les réponses',generate:'Générer mon plan',retry:'Réessayer',back:'Voir le plan enregistré',adult:'J’ai 18 ans ou plus et je souhaite des conseils généraux de fitness, pas un traitement médical.',consent:'J’accepte que Groq traite mes réponses et messages aux États-Unis. Je ne fournirai ni noms, ni coordonnées, ni dossiers médicaux.',continue:'Continuer le questionnaire',queued:'Votre plan est en attente. Vous pouvez partir et revenir ; votre demande est enregistrée.',failed:'Le plan n’a pas pu être terminé. Votre quota reste disponible. Réessayez plus tard.',error:'Impossible de charger ou d’enregistrer les informations. Réessayez.',adults:'TJAI est réservé aux adultes de 18–100 ans. Vérifiez âge, taille et poids.',terms:'$19.99 une fois · plans et journaux enregistrés · 5 réponses complètes par jour · une régénération par mois civil en Turquie. La capacité gratuite peut entraîner des délais.',buy:'Continuer vers le paiement sécurisé',payment:'Confirmation du paiement',pending:'En attente du paiement vérifié. Revenez après le paiement.',paid:'Paiement confirmé. Créez votre plan.',limit:'La régénération sera disponible le prochain mois civil en Turquie.',loading:'Chargement…',savedAt:'Enregistré',confirm:'Confirmer et continuer',disabled:'Cette fonction supplémentaire est actuellement indisponible.'}
};
const scope={
 en:'This version cannot create a plan for clinical conditions, underweight targets or custom dietary exclusions. No payment has been taken. Use a qualified clinician for those needs.',
 tr:'Bu sürüm klinik durumlar, düşük kilo hedefleri veya özel besin kısıtlamaları için plan oluşturamaz. Ödeme alınmadı. Bu ihtiyaçlar için bir sağlık uzmanına başvur.',
 ar:'لا ينشئ هذا الإصدار خططاً للحالات الطبية أو أهداف نقص الوزن أو الاستبعادات الغذائية الخاصة. لم يُحصّل أي مبلغ. استعن بمختص صحي لهذه الاحتياجات.',
 es:'Esta versión no crea planes para condiciones clínicas, objetivos de bajo peso ni exclusiones dietéticas especiales. No se ha cobrado. Consulta a un profesional para esas necesidades.',
 fr:'Cette version ne crée pas de plans pour des affections cliniques, des objectifs de poids insuffisant ou des exclusions alimentaires particulières. Aucun paiement n’a été prélevé. Consultez un professionnel pour ces besoins.'
};
const replies={en:'replies left today · resets at midnight Türkiye time',tr:'bugün kalan yanıt · Türkiye saatiyle gece yarısı yenilenir',ar:'ردود متبقية اليوم · تتجدد منتصف الليل بتوقيت تركيا',es:'respuestas restantes hoy · se renuevan a medianoche de Turquía',fr:'réponses restantes aujourd’hui · renouvelées à minuit en Turquie'};
const recovery={en:'If capacity is busy, recovery checks run about every five minutes.',tr:'Kapasite doluysa yaklaşık beş dakikada bir yeniden kontrol edilir.',ar:'عند ازدحام السعة، تجري إعادة المحاولة كل خمس دقائق تقريباً.',es:'Si la capacidad está ocupada, se comprueba de nuevo cada cinco minutos aproximadamente.',fr:'En cas de saturation, une nouvelle vérification a lieu environ toutes les cinq minutes.'};
const nutrition={en:'Our current food catalog cannot match these targets with your accepted foods and meal count. Review your preferences or meal count. No generation allowance was used.',tr:'Mevcut besin kataloğumuz, kabul ettiğin besinler ve öğün sayısıyla bu hedefleri karşılayamıyor. Tercihlerini veya öğün sayısını gözden geçir. Plan oluşturma hakkın kullanılmadı.',ar:'لا يستطيع كتالوجنا الحالي مطابقة هذه الأهداف مع الأطعمة المقبولة وعدد الوجبات. راجع تفضيلاتك أو عدد الوجبات. لم يُستخدم رصيد إنشاء الخطة.',es:'El catálogo actual no permite alcanzar estos objetivos con los alimentos aceptados y el número de comidas. Revisa tus preferencias o las comidas diarias. No se ha usado tu cupo.',fr:'Notre catalogue actuel ne permet pas d’atteindre ces objectifs avec vos aliments acceptés et ce nombre de repas. Revoyez vos préférences ou le nombre de repas. Votre quota reste disponible.'};
export const getTjaiFlowCopy=(locale:Locale)=>({...values[locale],scope:scope[locale],replies:replies[locale],recovery:recovery[locale],nutrition:nutrition[locale]});
