import type { Locale } from "@/lib/i18n";

const copy = {
  en: { title: "Your digital bundle", lead: "A training and nutrition PDF bundle. $10 USD, with any applicable tax shown at checkout.", select: "Choose your bundle", cta: "Continue to secure checkout", working: "Opening checkout…", closed: "Purchases are not available yet.", failed: "Checkout is unavailable. Please try again later.", pending: "We are waiting for payment confirmation. You can check again below.", paid: "Payment confirmed. Your bundle is available.", test: "Test receipt recorded. This did not purchase or unlock a bundle.", refunded: "This purchase was refunded. Access from this payment has ended.", review: "This payment needs review before access can be granted.", check: "Check payment status", downloads: "My bundles", trust: "Payment is handled by Lemon Squeezy. Access begins after payment verification.", testLabel: "Test checkout — no purchase or access grant" },
  tr: { title: "Dijital paketiniz", lead: "Antrenman ve beslenme PDF paketi. 10 USD; geçerli vergiler ödeme adımında gösterilir.", select: "Paketinizi seçin", cta: "Güvenli ödemeye devam et", working: "Ödeme açılıyor…", closed: "Satın alma henüz kullanılamıyor.", failed: "Ödeme kullanılamıyor. Lütfen daha sonra tekrar deneyin.", pending: "Ödeme onayı bekleniyor. Aşağıdan tekrar kontrol edebilirsiniz.", paid: "Ödeme onaylandı. Paketiniz hazır.", test: "Test kaydı alındı. Paket satın alınmadı veya açılmadı.", refunded: "Bu ödeme iade edildi. Bu ödemeye bağlı erişim sona erdi.", review: "Erişim verilmeden önce bu ödeme incelenmelidir.", check: "Ödeme durumunu kontrol et", downloads: "Paketlerim", trust: "Ödeme Lemon Squeezy tarafından alınır. Erişim ödeme doğrulandıktan sonra açılır.", testLabel: "Test ödemesi — satın alma veya erişim sağlamaz" },
  ar: { title: "حزمتك الرقمية", lead: "حزمة تدريب وتغذية بصيغة PDF. السعر 10 دولارات أمريكية، وتظهر الضرائب المطبقة عند الدفع.", select: "اختر حزمتك", cta: "متابعة إلى الدفع الآمن", working: "جارٍ فتح الدفع…", closed: "الشراء غير متاح بعد.", failed: "الدفع غير متاح. حاول لاحقاً.", pending: "ننتظر تأكيد الدفع. يمكنك التحقق مرة أخرى أدناه.", paid: "تم تأكيد الدفع. حزمتك متاحة.", test: "تم تسجيل إيصال تجريبي. لم يتم شراء الحزمة أو فتحها.", refunded: "تم رد هذه الدفعة وانتهى الوصول المرتبط بها.", review: "تحتاج هذه الدفعة إلى مراجعة قبل منح الوصول.", check: "تحقق من حالة الدفع", downloads: "حزمي", trust: "تتم معالجة الدفع عبر Lemon Squeezy. يبدأ الوصول بعد التحقق من الدفع.", testLabel: "دفع تجريبي — لا يشتري أو يفتح المحتوى" },
  es: { title: "Tu paquete digital", lead: "Un paquete PDF de entrenamiento y nutrición. 10 USD; los impuestos aplicables se muestran al pagar.", select: "Elige tu paquete", cta: "Continuar al pago seguro", working: "Abriendo pago…", closed: "Las compras aún no están disponibles.", failed: "El pago no está disponible. Inténtalo más tarde.", pending: "Esperamos la confirmación del pago. Puedes comprobarlo abajo.", paid: "Pago confirmado. Tu paquete está disponible.", test: "Recibo de prueba registrado. No se compró ni desbloqueó ningún paquete.", refunded: "Este pago se reembolsó. El acceso de esta compra ha terminado.", review: "Este pago requiere revisión antes de conceder acceso.", check: "Comprobar el pago", downloads: "Mis paquetes", trust: "Lemon Squeezy procesa el pago. El acceso comienza tras verificarlo.", testLabel: "Pago de prueba — sin compra ni acceso" },
  fr: { title: "Votre pack numérique", lead: "Un pack PDF d’entraînement et de nutrition. 10 USD ; les taxes applicables sont affichées au paiement.", select: "Choisissez votre pack", cta: "Continuer vers le paiement sécurisé", working: "Ouverture du paiement…", closed: "Les achats ne sont pas encore disponibles.", failed: "Le paiement est indisponible. Réessayez plus tard.", pending: "Nous attendons la confirmation du paiement. Vous pouvez vérifier ci-dessous.", paid: "Paiement confirmé. Votre pack est disponible.", test: "Reçu de test enregistré. Aucun pack n’a été acheté ou débloqué.", refunded: "Ce paiement a été remboursé. L’accès lié à cet achat est terminé.", review: "Ce paiement doit être examiné avant d’accorder l’accès.", check: "Vérifier le paiement", downloads: "Mes packs", trust: "Le paiement est traité par Lemon Squeezy. L’accès commence après vérification du paiement.", testLabel: "Paiement de test — aucun achat ni accès" }
};
export function getDigitalCheckoutCopy(locale: Locale) { return copy[locale]; }
