import {afterEach,describe,it,expect,vi} from 'vitest';
import {PROVIDER_POLICY,TJAI_AI_TASKS,TJAI_PROVIDER_UNAVAILABLE,isAnthropicConfigured,isOpenAIConfigured,isProviderConfigured,isTaskAvailable,providerUnavailableBody,resolveTaskProvider} from '@/lib/tjai/provider-policy';
afterEach(()=>vi.unstubAllEnvs());
describe('free-only provider policy',()=>{
 it('has a decision for each task and enables only plan/chat',()=>{for(const task of Object.values(TJAI_AI_TASKS)){expect(PROVIDER_POLICY[task].task).toBe(task);expect(PROVIDER_POLICY[task].provider).toBe(['plan_generate','chat_stream'].includes(task)?'open':'none');}});
 it('does not accept paid legacy keys as an available provider',()=>{vi.stubEnv('OPENAI_API_KEY','unused');vi.stubEnv('ANTHROPIC_API_KEY','unused');expect(isOpenAIConfigured()).toBe(false);expect(isAnthropicConfigured()).toBe(false);expect(isProviderConfigured('openai')).toBe(false);expect(isProviderConfigured('anthropic')).toBe(false);});
 it('requires explicit account enablement and ZDR confirmation',()=>{vi.stubEnv('TJAI_LLM_PRESET','groq');vi.stubEnv('TJAI_LLM_API_KEY','test-only');vi.stubEnv('TJAI_PROVIDER_ENABLED','false');vi.stubEnv('TJAI_GROQ_ZDR_CONFIRMED','false');expect(resolveTaskProvider('chat_stream')).toBe('none');vi.stubEnv('TJAI_PROVIDER_ENABLED','true');expect(isTaskAvailable('chat_stream')).toBe(false);vi.stubEnv('TJAI_GROQ_ZDR_CONFIRMED','true');expect(isTaskAvailable('chat_stream')).toBe(true);expect(isTaskAvailable('plan_generate')).toBe(true);});
 it.each(['ollama','openrouter','together','vllm'])('rejects %s routing under the selected v1 policy',(preset)=>{vi.stubEnv('TJAI_PROVIDER_ENABLED','true');vi.stubEnv('TJAI_GROQ_ZDR_CONFIRMED','true');vi.stubEnv('TJAI_LLM_API_KEY','test-only');vi.stubEnv('TJAI_LLM_PRESET',preset);expect(resolveTaskProvider('chat_stream')).toBe('none');});
 it('keeps hidden optional inference tasks disabled even with all keys',()=>{vi.stubEnv('TJAI_PROVIDER_ENABLED','true');vi.stubEnv('TJAI_GROQ_ZDR_CONFIRMED','true');vi.stubEnv('TJAI_LLM_PRESET','groq');vi.stubEnv('TJAI_LLM_API_KEY','test-only');for(const task of Object.values(TJAI_AI_TASKS).filter(t=>!['plan_generate','chat_stream'].includes(t)))expect(isTaskAvailable(task)).toBe(false);});
 it('provides a stable unavailable response',()=>{expect(providerUnavailableBody()).toMatchObject({code:TJAI_PROVIDER_UNAVAILABLE,error:expect.any(String)});});
});
