/** Durable generation safety: validation never spends a credit; PostgreSQL owns reservation/refund. */
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {NextRequest} from 'next/server';
const mocks=vi.hoisted(()=>({rpc:vi.fn(),access:vi.fn(),dispatch:vi.fn(),auth:vi.fn(),provider:vi.fn(),pass:vi.fn(),legacy:vi.fn()}));
const admin={rpc:mocks.rpc,from:vi.fn(()=>({select:vi.fn().mockReturnThis(),eq:vi.fn().mockReturnThis(),single:vi.fn().mockResolvedValue({data:{answers_json:{s1_age:29,s1_height:175,s1_weight:80}},error:null})}))};
vi.mock('@/lib/require-auth',()=>({requireAuth:mocks.auth}));
vi.mock('@/lib/supabase-server',()=>({getSupabaseServerClient:()=>admin}));
vi.mock('@/lib/tjai/server-access',()=>({getTjaiServerAccess:mocks.access}));
vi.mock('@/lib/tjai/worker-dispatch',()=>({dispatchTjaiWorker:mocks.dispatch}));
vi.mock('@/lib/tjai-pass',()=>({getTjaiPassAccess:mocks.pass}));
vi.mock('@/lib/tjai/legacy-access',()=>({getTjaiLegacyAccess:mocks.legacy}));
vi.mock('@/lib/tjai/free-provider',async original=>({...await original<typeof import('@/lib/tjai/free-provider')>(),callFreeGroq:mocks.provider}));
vi.mock('@/lib/tjai/compact-plan',()=>({compactPrompt:()=>({system:'test',user:'test'}),expandCompactPlan:()=>({plan:{summary:{}},metrics:{}})}));
import {POST} from '@/app/api/tjai/generate/route';
import {processNextTjaiJob} from '@/lib/tjai/jobs';
import {TjaiProviderError} from '@/lib/tjai/free-provider';
const user='11111111-1111-4111-8111-111111111111',intake='22222222-2222-4222-8222-222222222222',requestId='33333333-3333-4333-8333-333333333333';
const request=(body:unknown)=>new NextRequest('https://local.invalid/api/tjai/generate',{method:'POST',body:JSON.stringify(body),headers:{'Content-Type':'application/json'}});
const queued={id:requestId,user_id:user,intake_id:intake,kind:'credit',status:'queued'};
const claimed={...queued,status:'running',lease_token:'44444444-4444-4444-8444-444444444444'};
beforeEach(()=>{vi.clearAllMocks();mocks.rpc.mockReset();mocks.auth.mockResolvedValue({ok:true,user:{id:user}});mocks.access.mockResolvedValue({available:true,providerReady:true,workerReady:true,mode:'credit'});mocks.dispatch.mockResolvedValue(true);mocks.pass.mockResolvedValue({available:true,hasPass:true});mocks.legacy.mockResolvedValue({available:true,hasAccess:true});mocks.provider.mockResolvedValue('{}');});
describe('durable generation request safety',()=>{
 it('ignores a new-pass customer trying to choose legacy mode in the request',async()=>{mocks.access.mockResolvedValue({available:true,providerReady:true,workerReady:true,mode:'pass'});mocks.rpc.mockResolvedValue({data:queued,error:null});await POST(request({intakeId:intake,requestId,mode:'legacy'}));expect(mocks.rpc.mock.calls[0][1].p_mode).toBe('pass');});
 it('rejects invalid input before reserving or refunding credits',async()=>{expect((await POST(request(null))).status).toBe(400);expect(mocks.rpc).not.toHaveBeenCalled();expect(mocks.dispatch).not.toHaveBeenCalled();});
 it('rejects unavailable provider and worker before enqueue',async()=>{mocks.access.mockResolvedValueOnce({available:true,providerReady:false,workerReady:true,mode:'credit'});expect((await POST(request({intakeId:intake,requestId}))).status).toBe(503);mocks.access.mockResolvedValueOnce({available:true,providerReady:true,workerReady:false,mode:'credit'});expect((await POST(request({intakeId:intake,requestId}))).status).toBe(503);expect(mocks.rpc).not.toHaveBeenCalled();});
 it('delegates credit reservation to the single transactional enqueue RPC',async()=>{mocks.rpc.mockResolvedValue({data:queued,error:null});const r=await POST(request({intakeId:intake,requestId}));expect(r.status).toBe(202);expect(mocks.rpc.mock.calls).toEqual([['tjai_enqueue_job',{p_user:user,p_intake:intake,p_request:requestId,p_mode:'credit'}]]);expect(mocks.provider).not.toHaveBeenCalled();expect(mocks.dispatch).toHaveBeenCalledOnce();});
 it('leaves a durable queued job for recovery when immediate dispatch fails',async()=>{mocks.rpc.mockResolvedValue({data:queued,error:null});mocks.dispatch.mockResolvedValue(false);const r=await POST(request({intakeId:intake,requestId}));expect(r.status).toBe(202);expect((await r.json()).job.status).toBe('queued');expect(mocks.rpc).toHaveBeenCalledTimes(1);});
 it('surfaces failed enqueue without a compensating refund that could mint credits',async()=>{mocks.rpc.mockResolvedValue({data:null,error:{message:'database unavailable'}});expect((await POST(request({intakeId:intake,requestId}))).status).toBe(503);expect(mocks.rpc.mock.calls.map(c=>c[0])).toEqual(['tjai_enqueue_job']);expect(mocks.dispatch).not.toHaveBeenCalled();});
 it('preserves the idempotency key on repeated browser submissions',async()=>{mocks.rpc.mockResolvedValue({data:queued,error:null});await POST(request({intakeId:intake,requestId}));await POST(request({intakeId:intake,requestId}));expect(mocks.rpc.mock.calls[0]).toEqual(mocks.rpc.mock.calls[1]);});
});
describe('durable worker failure and refund boundary',()=>{
 it('checks current legacy eligibility before provider work even when the user also has a new pass',async()=>{mocks.rpc.mockResolvedValueOnce({data:{...claimed,kind:'legacy'},error:null}).mockResolvedValueOnce({data:{status:'failed'},error:null});mocks.legacy.mockResolvedValue({available:true,hasAccess:false});expect(await processNextTjaiJob(admin as never,'test')).toMatchObject({status:'failed'});expect(mocks.provider).not.toHaveBeenCalled();expect(mocks.rpc.mock.calls[1][1]).toMatchObject({p_error:'access_revoked',p_retry_seconds:0});});
 it('rejects infeasible historical intake before provider work and terminally releases its reservation',async()=>{admin.from.mockImplementationOnce(()=>({select:vi.fn().mockReturnThis(),eq:vi.fn().mockReturnThis(),single:vi.fn().mockResolvedValue({data:{answers_json:{s1_age:29,s1_height:220,s1_weight:300}},error:null})}));mocks.rpc.mockResolvedValueOnce({data:claimed,error:null}).mockResolvedValueOnce({data:{status:'failed'},error:null});expect(await processNextTjaiJob(admin as never,'test')).toMatchObject({status:'failed'});expect(mocks.provider).not.toHaveBeenCalled();expect(mocks.rpc.mock.calls[1][1]).toMatchObject({p_error:'nutrition_targets_unsupported',p_retry_seconds:0,p_plan:null});});
 it('finalizes provider failure through the leased database operation',async()=>{mocks.rpc.mockResolvedValueOnce({data:claimed,error:null}).mockResolvedValueOnce({data:{status:'failed'},error:null});mocks.provider.mockRejectedValueOnce(new TjaiProviderError('provider_rejected'));expect(await processNextTjaiJob(admin as never,'test')).toMatchObject({status:'failed'});expect(mocks.rpc.mock.calls[1]).toEqual(['tjai_finish_job',expect.objectContaining({p_job:claimed.id,p_lease:claimed.lease_token,p_plan:null,p_error:'provider_rejected',p_retry_seconds:0})]);expect(mocks.rpc.mock.calls.some(c=>c[0]==='grant_tjai_credit')).toBe(false);});
 it('requeues transient capacity failures without a route-level refund',async()=>{mocks.rpc.mockResolvedValueOnce({data:claimed,error:null}).mockResolvedValueOnce({data:{status:'queued'},error:null});mocks.provider.mockRejectedValueOnce(new TjaiProviderError('provider_capacity',65));expect(await processNextTjaiJob(admin as never,'test')).toMatchObject({status:'queued'});expect(mocks.rpc.mock.calls[1][1]).toMatchObject({p_retry_seconds:65});});
 it('requires persisted plan success and does not separately refund success',async()=>{mocks.rpc.mockResolvedValueOnce({data:claimed,error:null}).mockResolvedValueOnce({data:{status:'succeeded'},error:null});expect(await processNextTjaiJob(admin as never,'test')).toMatchObject({status:'succeeded'});expect(mocks.rpc.mock.calls.map(c=>c[0])).toEqual(['tjai_claim_job','tjai_finish_job']);expect(mocks.rpc.mock.calls[1][1].p_plan).toEqual({summary:{}});});
 it('does not call the provider for a pass revoked after enqueue',async()=>{mocks.rpc.mockResolvedValueOnce({data:{...claimed,kind:'initial'},error:null}).mockResolvedValueOnce({data:{status:'failed'},error:null});mocks.pass.mockResolvedValue({available:true,hasPass:false});expect(await processNextTjaiJob(admin as never,'test')).toMatchObject({status:'failed'});expect(mocks.provider).not.toHaveBeenCalled();expect(mocks.rpc.mock.calls[1][1]).toMatchObject({p_error:'access_revoked',p_retry_seconds:0});});
 it('treats a lost persistence acknowledgement as recovery pending, never delivered',async()=>{mocks.rpc.mockResolvedValueOnce({data:claimed,error:null}).mockResolvedValue({data:null,error:{message:'database unavailable'}});await expect(processNextTjaiJob(admin as never,'test')).rejects.toThrow('job_recovery_pending');});
});
// Exact-once credit refunds after provider failure and expired leases are exercised against
// the actual SQL migrations in tjai-database.integration.mjs, not a JavaScript counter.
