// GENERATED — do not edit by hand.
//
// Source: github.com/yuhonas/free-exercise-db, pinned to commit
//   b0eed061e1c832b3ed815fbaa4b45b3cdc14df49
// Licence: The Unlicense (public domain dedication) — no attribution required,
// commercial use unrestricted. Verified against the repo's LICENSE.md.
//
// Pinned to a commit, never @main: this is product data, and an upstream edit
// must not silently change what TJAI is allowed to prescribe.
//
// Trimmed from the 978 KB source to 83 KB by dropping instructions, images,
// ids, force and mechanic. What survives is what validation needs: the
// canonical name, primary muscles, required equipment, difficulty and category.
//
// NOTE: this is a CATALOGUE, not the coaching library. src/lib/programs/
// exercises/library.ts holds the hand-authored, localized entries with form
// cues and safety warnings — that is the product. This list exists so the plan
// validator can tell a real movement from a hallucinated one.

/** Muscle vocabulary used by the catalogue (free-exercise-db's 17 groups). */
export type CatalogMuscle =
  | "abdominals" | "abductors" | "adductors" | "biceps" | "calves" | "chest"
  | "forearms" | "glutes" | "hamstrings" | "lats" | "lower back" | "middle back"
  | "neck" | "quadriceps" | "shoulders" | "traps" | "triceps";

export type CatalogLevel = "beginner" | "intermediate" | "expert";

export type CatalogCategory =
  | "cardio" | "olympic weightlifting" | "plyometrics" | "powerlifting"
  | "strength" | "stretching" | "strongman";

export type CatalogExercise = {
  /** Canonical display name. */
  n: string;
  /** Primary muscles worked. */
  m: CatalogMuscle[];
  /** Required equipment; null where the source records none. */
  e: string | null;
  l: CatalogLevel;
  c: CatalogCategory;
};

export const EXERCISE_CATALOG: readonly CatalogExercise[] = [
  {"n":"3/4 Sit-Up","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"90/90 Hamstring","m":["hamstrings"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Ab Crunch Machine","m":["abdominals"],"e":"machine","l":"intermediate","c":"strength"},
  {"n":"Ab Roller","m":["abdominals"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Adductor","m":["adductors"],"e":"foam roll","l":"intermediate","c":"stretching"},
  {"n":"Adductor/Groin","m":["adductors"],"e":null,"l":"intermediate","c":"stretching"},
  {"n":"Advanced Kettlebell Windmill","m":["abdominals"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Air Bike","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"All Fours Quad Stretch","m":["quadriceps"],"e":"body only","l":"intermediate","c":"stretching"},
  {"n":"Alternate Hammer Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Alternate Heel Touchers","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Alternate Incline Dumbbell Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Alternate Leg Diagonal Bound","m":["quadriceps"],"e":null,"l":"beginner","c":"plyometrics"},
  {"n":"Alternating Cable Shoulder Press","m":["shoulders"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Alternating Deltoid Raise","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Alternating Floor Press","m":["chest"],"e":"kettlebells","l":"beginner","c":"strength"},
  {"n":"Alternating Hang Clean","m":["hamstrings"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Alternating Kettlebell Press","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Alternating Kettlebell Row","m":["middle back"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Alternating Renegade Row","m":["middle back"],"e":"kettlebells","l":"expert","c":"strength"},
  {"n":"Ankle Circles","m":["calves"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Ankle On The Knee","m":["glutes"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Anterior Tibialis-SMR","m":["calves"],"e":"other","l":"intermediate","c":"stretching"},
  {"n":"Anti-Gravity Press","m":["shoulders"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Arm Circles","m":["shoulders"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Arnold Dumbbell Press","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Around The Worlds","m":["chest"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Atlas Stone Trainer","m":["lower back"],"e":"other","l":"intermediate","c":"strongman"},
  {"n":"Atlas Stones","m":["lower back"],"e":"other","l":"expert","c":"strongman"},
  {"n":"Axle Deadlift","m":["lower back"],"e":"other","l":"intermediate","c":"strongman"},
  {"n":"Back Flyes - With Bands","m":["shoulders"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Backward Drag","m":["quadriceps"],"e":"other","l":"beginner","c":"strongman"},
  {"n":"Backward Medicine Ball Throw","m":["shoulders"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Balance Board","m":["calves"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Ball Leg Curl","m":["hamstrings"],"e":"exercise ball","l":"beginner","c":"strength"},
  {"n":"Band Assisted Pull-Up","m":["lats"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Band Good Morning","m":["hamstrings"],"e":"bands","l":"beginner","c":"powerlifting"},
  {"n":"Band Good Morning (Pull Through)","m":["hamstrings"],"e":"bands","l":"beginner","c":"powerlifting"},
  {"n":"Band Hip Adductions","m":["adductors"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Band Pull Apart","m":["shoulders"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Band Skull Crusher","m":["triceps"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Barbell Ab Rollout","m":["abdominals"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Barbell Ab Rollout - On Knees","m":["abdominals"],"e":"barbell","l":"expert","c":"strength"},
  {"n":"Barbell Bench Press - Medium Grip","m":["chest"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Barbell Curl","m":["biceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Barbell Curls Lying Against An Incline","m":["biceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Barbell Deadlift","m":["lower back"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Barbell Full Squat","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Barbell Glute Bridge","m":["glutes"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Barbell Guillotine Bench Press","m":["chest"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Barbell Hack Squat","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Barbell Hip Thrust","m":["glutes"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Barbell Incline Bench Press - Medium Grip","m":["chest"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Barbell Incline Shoulder Raise","m":["shoulders"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Barbell Lunge","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Barbell Rear Delt Row","m":["shoulders"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Barbell Rollout from Bench","m":["abdominals"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Barbell Seated Calf Raise","m":["calves"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Barbell Shoulder Press","m":["shoulders"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Barbell Shrug","m":["traps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Barbell Shrug Behind The Back","m":["traps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Barbell Side Bend","m":["abdominals"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Barbell Side Split Squat","m":["quadriceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Barbell Squat","m":["quadriceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Barbell Squat To A Bench","m":["quadriceps"],"e":"barbell","l":"expert","c":"strength"},
  {"n":"Barbell Step Ups","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Barbell Walking Lunge","m":["quadriceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Battling Ropes","m":["shoulders"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Bear Crawl Sled Drags","m":["quadriceps"],"e":"other","l":"beginner","c":"strongman"},
  {"n":"Behind Head Chest Stretch","m":["chest"],"e":"other","l":"expert","c":"stretching"},
  {"n":"Bench Dips","m":["triceps"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Bench Jump","m":["quadriceps"],"e":"body only","l":"intermediate","c":"plyometrics"},
  {"n":"Bench Press - Powerlifting","m":["triceps"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Bench Press - With Bands","m":["chest"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Bench Press with Chains","m":["triceps"],"e":"barbell","l":"expert","c":"powerlifting"},
  {"n":"Bench Sprint","m":["quadriceps"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Bent Over Barbell Row","m":["middle back"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Bent Over Dumbbell Rear Delt Raise With Head On Bench","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Bent Over Low-Pulley Side Lateral","m":["shoulders"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Bent Over One-Arm Long Bar Row","m":["middle back"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Bent Over Two-Arm Long Bar Row","m":["middle back"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Bent Over Two-Dumbbell Row","m":["middle back"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Bent Over Two-Dumbbell Row With Palms In","m":["middle back"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Bent Press","m":["abdominals"],"e":"kettlebells","l":"expert","c":"strength"},
  {"n":"Bent-Arm Barbell Pullover","m":["lats"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Bent-Arm Dumbbell Pullover","m":["chest"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Bent-Knee Hip Raise","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Bicycling","m":["quadriceps"],"e":"other","l":"beginner","c":"cardio"},
  {"n":"Bicycling, Stationary","m":["quadriceps"],"e":"machine","l":"beginner","c":"cardio"},
  {"n":"Board Press","m":["triceps"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Body Tricep Press","m":["triceps"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Body-Up","m":["triceps"],"e":"body only","l":"intermediate","c":"strength"},
  {"n":"Bodyweight Flyes","m":["chest"],"e":"e-z curl bar","l":"intermediate","c":"strength"},
  {"n":"Bodyweight Mid Row","m":["middle back"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Bodyweight Squat","m":["quadriceps"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Bodyweight Walking Lunge","m":["quadriceps"],"e":null,"l":"beginner","c":"strength"},
  {"n":"Bosu Ball Cable Crunch With Side Bends","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Bottoms Up","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Bottoms-Up Clean From The Hang Position","m":["forearms"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Box Jump (Multiple Response)","m":["hamstrings"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Box Skip","m":["hamstrings"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Box Squat","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Box Squat with Bands","m":["quadriceps"],"e":"barbell","l":"expert","c":"powerlifting"},
  {"n":"Box Squat with Chains","m":["quadriceps"],"e":"barbell","l":"expert","c":"strength"},
  {"n":"Brachialis-SMR","m":["biceps"],"e":"foam roll","l":"intermediate","c":"stretching"},
  {"n":"Bradford/Rocky Presses","m":["shoulders"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Butt Lift (Bridge)","m":["glutes"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Butt-Ups","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Butterfly","m":["chest"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Cable Chest Press","m":["chest"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Crossover","m":["chest"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Crunch","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Deadlifts","m":["quadriceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Hammer Curls - Rope Attachment","m":["biceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Hip Adduction","m":["quadriceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Incline Pushdown","m":["lats"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Incline Triceps Extension","m":["triceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Internal Rotation","m":["shoulders"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Iron Cross","m":["chest"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Judo Flip","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Lying Triceps Extension","m":["triceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable One Arm Tricep Extension","m":["triceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Preacher Curl","m":["biceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Rear Delt Fly","m":["shoulders"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Reverse Crunch","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Rope Overhead Triceps Extension","m":["triceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Rope Rear-Delt Rows","m":["shoulders"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Russian Twists","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Seated Crunch","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Seated Lateral Raise","m":["shoulders"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Shoulder Press","m":["shoulders"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Shrugs","m":["traps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Cable Wrist Curl","m":["forearms"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Calf Press","m":["calves"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Calf Press On The Leg Press Machine","m":["calves"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Calf Raise On A Dumbbell","m":["calves"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Calf Raises - With Bands","m":["calves"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Calf Stretch Elbows Against Wall","m":["calves"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Calf Stretch Hands Against Wall","m":["calves"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Calf-Machine Shoulder Shrug","m":["traps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Calves-SMR","m":["calves"],"e":"foam roll","l":"intermediate","c":"stretching"},
  {"n":"Car Deadlift","m":["quadriceps"],"e":"other","l":"intermediate","c":"strongman"},
  {"n":"Car Drivers","m":["shoulders"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Carioca Quick Step","m":["adductors"],"e":null,"l":"beginner","c":"plyometrics"},
  {"n":"Cat Stretch","m":["lower back"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Catch and Overhead Throw","m":["lats"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Chain Handle Extension","m":["triceps"],"e":"other","l":"intermediate","c":"powerlifting"},
  {"n":"Chain Press","m":["chest"],"e":"other","l":"intermediate","c":"powerlifting"},
  {"n":"Chair Leg Extended Stretch","m":["hamstrings"],"e":"other","l":"beginner","c":"stretching"},
  {"n":"Chair Lower Back Stretch","m":["lats"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Chair Squat","m":["quadriceps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Chair Upper Body Stretch","m":["shoulders"],"e":"other","l":"beginner","c":"stretching"},
  {"n":"Chest And Front Of Shoulder Stretch","m":["chest"],"e":"other","l":"beginner","c":"stretching"},
  {"n":"Chest Push (multiple response)","m":["chest"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Chest Push (single response)","m":["chest"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Chest Push from 3 point stance","m":["chest"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Chest Push with Run Release","m":["chest"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Chest Stretch on Stability Ball","m":["chest"],"e":"exercise ball","l":"beginner","c":"stretching"},
  {"n":"Child's Pose","m":["lower back"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Chin To Chest Stretch","m":["neck"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Chin-Up","m":["lats"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Circus Bell","m":["shoulders"],"e":"other","l":"expert","c":"strongman"},
  {"n":"Clean","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Clean and Jerk","m":["shoulders"],"e":"barbell","l":"expert","c":"olympic weightlifting"},
  {"n":"Clean and Press","m":["shoulders"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Clean Deadlift","m":["hamstrings"],"e":"barbell","l":"beginner","c":"olympic weightlifting"},
  {"n":"Clean from Blocks","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Clean Pull","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Clean Shrug","m":["traps"],"e":"barbell","l":"beginner","c":"olympic weightlifting"},
  {"n":"Clock Push-Up","m":["chest"],"e":"body only","l":"intermediate","c":"strength"},
  {"n":"Close-Grip Barbell Bench Press","m":["triceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Close-Grip Dumbbell Press","m":["triceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Close-Grip EZ Bar Curl","m":["biceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Close-Grip EZ-Bar Curl with Band","m":["biceps"],"e":"e-z curl bar","l":"beginner","c":"strength"},
  {"n":"Close-Grip EZ-Bar Press","m":["triceps"],"e":"e-z curl bar","l":"beginner","c":"strength"},
  {"n":"Close-Grip Front Lat Pulldown","m":["lats"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Close-Grip Push-Up off of a Dumbbell","m":["triceps"],"e":"body only","l":"intermediate","c":"strength"},
  {"n":"Close-Grip Standing Barbell Curl","m":["biceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Cocoons","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Conan's Wheel","m":["quadriceps"],"e":"other","l":"intermediate","c":"strongman"},
  {"n":"Concentration Curls","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Cross Body Hammer Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Cross Over - With Bands","m":["chest"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Cross-Body Crunch","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Crossover Reverse Lunge","m":["lower back"],"e":null,"l":"intermediate","c":"stretching"},
  {"n":"Crucifix","m":["shoulders"],"e":"other","l":"beginner","c":"strongman"},
  {"n":"Crunch - Hands Overhead","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Crunch - Legs On Exercise Ball","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Crunches","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Cuban Press","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dancer's Stretch","m":["lower back"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Dead Bug","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Deadlift with Bands","m":["lower back"],"e":"barbell","l":"expert","c":"powerlifting"},
  {"n":"Deadlift with Chains","m":["lower back"],"e":"barbell","l":"expert","c":"powerlifting"},
  {"n":"Decline Barbell Bench Press","m":["chest"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Decline Close-Grip Bench To Skull Crusher","m":["triceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Decline Crunch","m":["abdominals"],"e":"body only","l":"intermediate","c":"strength"},
  {"n":"Decline Dumbbell Bench Press","m":["chest"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Decline Dumbbell Flyes","m":["chest"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Decline Dumbbell Triceps Extension","m":["triceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Decline EZ Bar Triceps Extension","m":["triceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Decline Oblique Crunch","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Decline Push-Up","m":["chest"],"e":null,"l":"beginner","c":"strength"},
  {"n":"Decline Reverse Crunch","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Decline Smith Press","m":["chest"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Deficit Deadlift","m":["lower back"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Depth Jump Leap","m":["quadriceps"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Dip Machine","m":["triceps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Dips - Chest Version","m":["chest"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Dips - Triceps Version","m":["triceps"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Donkey Calf Raises","m":["calves"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Double Kettlebell Alternating Hang Clean","m":["hamstrings"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Double Kettlebell Jerk","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Double Kettlebell Push Press","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Double Kettlebell Snatch","m":["shoulders"],"e":"kettlebells","l":"expert","c":"strength"},
  {"n":"Double Kettlebell Windmill","m":["abdominals"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Double Leg Butt Kick","m":["quadriceps"],"e":"body only","l":"beginner","c":"plyometrics"},
  {"n":"Downward Facing Balance","m":["glutes"],"e":"exercise ball","l":"intermediate","c":"strength"},
  {"n":"Drag Curl","m":["biceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Drop Push","m":["chest"],"e":"other","l":"intermediate","c":"plyometrics"},
  {"n":"Dumbbell Alternate Bicep Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Bench Press","m":["chest"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Bench Press with Neutral Grip","m":["chest"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Bicep Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Clean","m":["hamstrings"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dumbbell Floor Press","m":["triceps"],"e":"dumbbell","l":"intermediate","c":"powerlifting"},
  {"n":"Dumbbell Flyes","m":["chest"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Incline Row","m":["middle back"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Incline Shoulder Raise","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Lunges","m":["quadriceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Lying One-Arm Rear Lateral Raise","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dumbbell Lying Pronation","m":["forearms"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dumbbell Lying Rear Lateral Raise","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dumbbell Lying Supination","m":["forearms"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dumbbell One-Arm Shoulder Press","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dumbbell One-Arm Triceps Extension","m":["triceps"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dumbbell One-Arm Upright Row","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dumbbell Prone Incline Curl","m":["biceps"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dumbbell Raise","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Rear Lunge","m":["quadriceps"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dumbbell Scaption","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Seated Box Jump","m":["quadriceps"],"e":"dumbbell","l":"intermediate","c":"plyometrics"},
  {"n":"Dumbbell Seated One-Leg Calf Raise","m":["calves"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Shoulder Press","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dumbbell Shrug","m":["traps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Side Bend","m":["abdominals"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Squat","m":["quadriceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dumbbell Squat To A Bench","m":["quadriceps"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dumbbell Step Ups","m":["quadriceps"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Dumbbell Tricep Extension -Pronated Grip","m":["triceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Dynamic Back Stretch","m":["lats"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Dynamic Chest Stretch","m":["chest"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Elbow Circles","m":["shoulders"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Elbow to Knee","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Elbows Back","m":["chest"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Elevated Back Lunge","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Elevated Cable Rows","m":["lats"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Elliptical Trainer","m":["quadriceps"],"e":"machine","l":"intermediate","c":"cardio"},
  {"n":"Exercise Ball Crunch","m":["abdominals"],"e":"exercise ball","l":"beginner","c":"strength"},
  {"n":"Exercise Ball Pull-In","m":["abdominals"],"e":"exercise ball","l":"beginner","c":"strength"},
  {"n":"Extended Range One-Arm Kettlebell Floor Press","m":["chest"],"e":"kettlebells","l":"beginner","c":"strength"},
  {"n":"External Rotation","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"External Rotation with Band","m":["shoulders"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"External Rotation with Cable","m":["shoulders"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"EZ-Bar Curl","m":["biceps"],"e":"e-z curl bar","l":"beginner","c":"strength"},
  {"n":"EZ-Bar Skullcrusher","m":["triceps"],"e":"e-z curl bar","l":"beginner","c":"strength"},
  {"n":"Face Pull","m":["shoulders"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Farmer's Walk","m":["forearms"],"e":"other","l":"intermediate","c":"strongman"},
  {"n":"Fast Skipping","m":["quadriceps"],"e":"body only","l":"beginner","c":"plyometrics"},
  {"n":"Finger Curls","m":["forearms"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Flat Bench Cable Flyes","m":["chest"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Flat Bench Leg Pull-In","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Flat Bench Lying Leg Raise","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Flexor Incline Dumbbell Curls","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Floor Glute-Ham Raise","m":["hamstrings"],"e":null,"l":"intermediate","c":"strength"},
  {"n":"Floor Press","m":["triceps"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Floor Press with Chains","m":["triceps"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Flutter Kicks","m":["glutes"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Foot-SMR","m":["calves"],"e":"other","l":"intermediate","c":"stretching"},
  {"n":"Forward Drag with Press","m":["chest"],"e":"other","l":"intermediate","c":"strongman"},
  {"n":"Frankenstein Squat","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Freehand Jump Squat","m":["quadriceps"],"e":"body only","l":"intermediate","c":"strength"},
  {"n":"Frog Hops","m":["quadriceps"],"e":null,"l":"intermediate","c":"stretching"},
  {"n":"Frog Sit-Ups","m":["abdominals"],"e":"body only","l":"intermediate","c":"strength"},
  {"n":"Front Barbell Squat","m":["quadriceps"],"e":"barbell","l":"expert","c":"strength"},
  {"n":"Front Barbell Squat To A Bench","m":["quadriceps"],"e":"barbell","l":"expert","c":"strength"},
  {"n":"Front Box Jump","m":["hamstrings"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Front Cable Raise","m":["shoulders"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Front Cone Hops (or hurdle hops)","m":["quadriceps"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Front Dumbbell Raise","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Front Incline Dumbbell Raise","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Front Leg Raises","m":["hamstrings"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Front Plate Raise","m":["shoulders"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Front Raise And Pullover","m":["chest"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Front Squat (Clean Grip)","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Front Squats With Two Kettlebells","m":["quadriceps"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Front Two-Dumbbell Raise","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Full Range-Of-Motion Lat Pulldown","m":["lats"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Gironda Sternum Chins","m":["lats"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Glute Ham Raise","m":["hamstrings"],"e":"machine","l":"intermediate","c":"powerlifting"},
  {"n":"Glute Kickback","m":["glutes"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Goblet Squat","m":["quadriceps"],"e":"kettlebells","l":"beginner","c":"strength"},
  {"n":"Good Morning","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Good Morning off Pins","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Gorilla Chin/Crunch","m":["abdominals"],"e":"body only","l":"intermediate","c":"strength"},
  {"n":"Groin and Back Stretch","m":["adductors"],"e":null,"l":"intermediate","c":"stretching"},
  {"n":"Groiners","m":["adductors"],"e":"body only","l":"intermediate","c":"stretching"},
  {"n":"Hack Squat","m":["quadriceps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Hammer Curls","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Hammer Grip Incline DB Bench Press","m":["chest"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Hamstring Stretch","m":["hamstrings"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Hamstring-SMR","m":["hamstrings"],"e":"foam roll","l":"beginner","c":"stretching"},
  {"n":"Handstand Push-Ups","m":["shoulders"],"e":"body only","l":"expert","c":"strength"},
  {"n":"Hang Clean","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Hang Clean - Below the Knees","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Hang Snatch","m":["hamstrings"],"e":"barbell","l":"expert","c":"olympic weightlifting"},
  {"n":"Hang Snatch - Below Knees","m":["hamstrings"],"e":"barbell","l":"expert","c":"olympic weightlifting"},
  {"n":"Hanging Bar Good Morning","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Hanging Leg Raise","m":["abdominals"],"e":"body only","l":"expert","c":"strength"},
  {"n":"Hanging Pike","m":["abdominals"],"e":"body only","l":"expert","c":"strength"},
  {"n":"Heaving Snatch Balance","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Heavy Bag Thrust","m":["chest"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"High Cable Curls","m":["biceps"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Hip Circles (prone)","m":["abductors"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Hip Extension with Bands","m":["glutes"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Hip Flexion with Band","m":["quadriceps"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Hip Lift with Band","m":["glutes"],"e":"bands","l":"beginner","c":"powerlifting"},
  {"n":"Hug A Ball","m":["lower back"],"e":"exercise ball","l":"beginner","c":"stretching"},
  {"n":"Hug Knees To Chest","m":["lower back"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Hurdle Hops","m":["hamstrings"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Hyperextensions (Back Extensions)","m":["lower back"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Hyperextensions With No Hyperextension Bench","m":["lower back"],"e":"body only","l":"intermediate","c":"strength"},
  {"n":"Iliotibial Tract-SMR","m":["abductors"],"e":"foam roll","l":"intermediate","c":"stretching"},
  {"n":"Inchworm","m":["hamstrings"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Incline Barbell Triceps Extension","m":["triceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Incline Bench Pull","m":["middle back"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Incline Cable Chest Press","m":["chest"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Incline Cable Flye","m":["chest"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Incline Dumbbell Bench With Palms Facing In","m":["chest"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Incline Dumbbell Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Incline Dumbbell Flyes","m":["chest"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Incline Dumbbell Flyes - With A Twist","m":["chest"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Incline Dumbbell Press","m":["chest"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Incline Hammer Curls","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Incline Inner Biceps Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Incline Push-Up","m":["chest"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Incline Push-Up Close-Grip","m":["triceps"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Incline Push-Up Depth Jump","m":["chest"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Incline Push-Up Medium","m":["chest"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Incline Push-Up Reverse Grip","m":["chest"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Incline Push-Up Wide","m":["chest"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Intermediate Groin Stretch","m":["hamstrings"],"e":"other","l":"intermediate","c":"stretching"},
  {"n":"Intermediate Hip Flexor and Quad Stretch","m":["quadriceps"],"e":"other","l":"intermediate","c":"stretching"},
  {"n":"Internal Rotation with Band","m":["shoulders"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Inverted Row","m":["middle back"],"e":null,"l":"beginner","c":"strength"},
  {"n":"Inverted Row with Straps","m":["middle back"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Iron Cross","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Iron Crosses (stretch)","m":["quadriceps"],"e":null,"l":"intermediate","c":"stretching"},
  {"n":"Isometric Chest Squeezes","m":["chest"],"e":"body only","l":"beginner","c":"plyometrics"},
  {"n":"Isometric Neck Exercise - Front And Back","m":["neck"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Isometric Neck Exercise - Sides","m":["neck"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Isometric Wipers","m":["chest"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"IT Band and Glute Stretch","m":["abductors"],"e":"other","l":"intermediate","c":"stretching"},
  {"n":"Jackknife Sit-Up","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Janda Sit-Up","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Jefferson Squats","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Jerk Balance","m":["shoulders"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Jerk Dip Squat","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"JM Press","m":["triceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Jogging, Treadmill","m":["quadriceps"],"e":"machine","l":"beginner","c":"cardio"},
  {"n":"Keg Load","m":["lower back"],"e":"other","l":"intermediate","c":"strongman"},
  {"n":"Kettlebell Arnold Press","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Kettlebell Dead Clean","m":["hamstrings"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Kettlebell Figure 8","m":["abdominals"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Kettlebell Hang Clean","m":["hamstrings"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Kettlebell One-Legged Deadlift","m":["hamstrings"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Kettlebell Pass Between The Legs","m":["abdominals"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Kettlebell Pirate Ships","m":["shoulders"],"e":"kettlebells","l":"beginner","c":"strength"},
  {"n":"Kettlebell Pistol Squat","m":["quadriceps"],"e":"kettlebells","l":"expert","c":"strength"},
  {"n":"Kettlebell Seated Press","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Kettlebell Seesaw Press","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Kettlebell Sumo High Pull","m":["traps"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Kettlebell Thruster","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Kettlebell Turkish Get-Up (Lunge style)","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Kettlebell Turkish Get-Up (Squat style)","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Kettlebell Windmill","m":["abdominals"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Kipping Muscle Up","m":["lats"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Knee Across The Body","m":["glutes"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Knee Circles","m":["calves"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Knee Tuck Jump","m":["hamstrings"],"e":"body only","l":"beginner","c":"plyometrics"},
  {"n":"Knee/Hip Raise On Parallel Bars","m":["abdominals"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Kneeling Arm Drill","m":["shoulders"],"e":null,"l":"beginner","c":"plyometrics"},
  {"n":"Kneeling Cable Crunch With Alternating Oblique Twists","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Kneeling Cable Triceps Extension","m":["triceps"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Kneeling Forearm Stretch","m":["forearms"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Kneeling High Pulley Row","m":["lats"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Kneeling Hip Flexor","m":["quadriceps"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Kneeling Jump Squat","m":["glutes"],"e":"barbell","l":"expert","c":"olympic weightlifting"},
  {"n":"Kneeling Single-Arm High Pulley Row","m":["lats"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Kneeling Squat","m":["glutes"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Landmine 180's","m":["abdominals"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Landmine Linear Jammer","m":["shoulders"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Lateral Bound","m":["adductors"],"e":"body only","l":"beginner","c":"plyometrics"},
  {"n":"Lateral Box Jump","m":["adductors"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Lateral Cone Hops","m":["adductors"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Lateral Raise - With Bands","m":["shoulders"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Latissimus Dorsi-SMR","m":["lats"],"e":"foam roll","l":"beginner","c":"stretching"},
  {"n":"Leg Extensions","m":["quadriceps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Leg Lift","m":["glutes"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Leg Press","m":["quadriceps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Leg Pull-In","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Leg-Over Floor Press","m":["chest"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Leg-Up Hamstring Stretch","m":["hamstrings"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Leverage Chest Press","m":["chest"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Leverage Deadlift","m":["quadriceps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Leverage Decline Chest Press","m":["chest"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Leverage High Row","m":["middle back"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Leverage Incline Chest Press","m":["chest"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Leverage Iso Row","m":["lats"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Leverage Shoulder Press","m":["shoulders"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Leverage Shrug","m":["traps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Linear 3-Part Start Technique","m":["hamstrings"],"e":null,"l":"beginner","c":"plyometrics"},
  {"n":"Linear Acceleration Wall Drill","m":["hamstrings"],"e":null,"l":"beginner","c":"plyometrics"},
  {"n":"Linear Depth Jump","m":["quadriceps"],"e":"other","l":"intermediate","c":"plyometrics"},
  {"n":"Log Lift","m":["shoulders"],"e":"other","l":"intermediate","c":"strongman"},
  {"n":"London Bridges","m":["lats"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Looking At Ceiling","m":["quadriceps"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Low Cable Crossover","m":["chest"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Low Cable Triceps Extension","m":["triceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Low Pulley Row To Neck","m":["shoulders"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Lower Back Curl","m":["abdominals"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Lower Back-SMR","m":["lower back"],"e":"foam roll","l":"beginner","c":"stretching"},
  {"n":"Lunge Pass Through","m":["hamstrings"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Lunge Sprint","m":["quadriceps"],"e":"machine","l":"intermediate","c":"strength"},
  {"n":"Lying Bent Leg Groin","m":["adductors"],"e":"other","l":"expert","c":"stretching"},
  {"n":"Lying Cable Curl","m":["biceps"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Lying Cambered Barbell Row","m":["middle back"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Lying Close-Grip Bar Curl On High Pulley","m":["biceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Lying Close-Grip Barbell Triceps Extension Behind The Head","m":["triceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Lying Close-Grip Barbell Triceps Press To Chin","m":["triceps"],"e":"e-z curl bar","l":"intermediate","c":"strength"},
  {"n":"Lying Crossover","m":["abductors"],"e":"body only","l":"expert","c":"stretching"},
  {"n":"Lying Dumbbell Tricep Extension","m":["triceps"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Lying Face Down Plate Neck Resistance","m":["neck"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Lying Face Up Plate Neck Resistance","m":["neck"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Lying Glute","m":["glutes"],"e":"body only","l":"expert","c":"stretching"},
  {"n":"Lying Hamstring","m":["hamstrings"],"e":"other","l":"expert","c":"stretching"},
  {"n":"Lying High Bench Barbell Curl","m":["biceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Lying Leg Curls","m":["hamstrings"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Lying Machine Squat","m":["quadriceps"],"e":"machine","l":"intermediate","c":"strength"},
  {"n":"Lying One-Arm Lateral Raise","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Lying Prone Quadriceps","m":["quadriceps"],"e":"body only","l":"expert","c":"stretching"},
  {"n":"Lying Rear Delt Raise","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Lying Supine Dumbbell Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Lying T-Bar Row","m":["middle back"],"e":"machine","l":"intermediate","c":"strength"},
  {"n":"Lying Triceps Press","m":["triceps"],"e":"e-z curl bar","l":"intermediate","c":"strength"},
  {"n":"Machine Bench Press","m":["chest"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Machine Bicep Curl","m":["biceps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Machine Preacher Curls","m":["biceps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Machine Shoulder (Military) Press","m":["shoulders"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Machine Triceps Extension","m":["triceps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Medicine Ball Chest Pass","m":["chest"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Medicine Ball Full Twist","m":["abdominals"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Medicine Ball Scoop Throw","m":["shoulders"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Middle Back Shrug","m":["middle back"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Middle Back Stretch","m":["middle back"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Mixed Grip Chin","m":["middle back"],"e":"other","l":"expert","c":"strength"},
  {"n":"Monster Walk","m":["abductors"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Mountain Climbers","m":["quadriceps"],"e":null,"l":"beginner","c":"plyometrics"},
  {"n":"Moving Claw Series","m":["hamstrings"],"e":null,"l":"beginner","c":"plyometrics"},
  {"n":"Muscle Snatch","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Muscle Up","m":["lats"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Narrow Stance Hack Squats","m":["quadriceps"],"e":"machine","l":"intermediate","c":"strength"},
  {"n":"Narrow Stance Leg Press","m":["quadriceps"],"e":"machine","l":"intermediate","c":"strength"},
  {"n":"Narrow Stance Squats","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Natural Glute Ham Raise","m":["hamstrings"],"e":"body only","l":"intermediate","c":"strength"},
  {"n":"Neck Press","m":["chest"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Neck-SMR","m":["neck"],"e":"other","l":"intermediate","c":"stretching"},
  {"n":"Oblique Crunches","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Oblique Crunches - On The Floor","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Olympic Squat","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"On Your Side Quad Stretch","m":["quadriceps"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"On-Your-Back Quad Stretch","m":["quadriceps"],"e":"other","l":"beginner","c":"stretching"},
  {"n":"One Arm Against Wall","m":["lats"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"One Arm Chin-Up","m":["middle back"],"e":"other","l":"expert","c":"strength"},
  {"n":"One Arm Dumbbell Bench Press","m":["chest"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"One Arm Dumbbell Preacher Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"One Arm Floor Press","m":["triceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"One Arm Lat Pulldown","m":["lats"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"One Arm Pronated Dumbbell Triceps Extension","m":["triceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"One Arm Supinated Dumbbell Triceps Extension","m":["triceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"One Half Locust","m":["quadriceps"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"One Handed Hang","m":["lats"],"e":"other","l":"beginner","c":"stretching"},
  {"n":"One Knee To Chest","m":["glutes"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"One Leg Barbell Squat","m":["quadriceps"],"e":"barbell","l":"expert","c":"strength"},
  {"n":"One-Arm Dumbbell Row","m":["middle back"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"One-Arm Flat Bench Dumbbell Flye","m":["chest"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"One-Arm High-Pulley Cable Side Bends","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"One-Arm Incline Lateral Raise","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"One-Arm Kettlebell Clean","m":["hamstrings"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"One-Arm Kettlebell Clean and Jerk","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"One-Arm Kettlebell Floor Press","m":["chest"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"One-Arm Kettlebell Jerk","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"One-Arm Kettlebell Military Press To The Side","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"One-Arm Kettlebell Para Press","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"One-Arm Kettlebell Push Press","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"One-Arm Kettlebell Row","m":["middle back"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"One-Arm Kettlebell Snatch","m":["shoulders"],"e":"kettlebells","l":"expert","c":"strength"},
  {"n":"One-Arm Kettlebell Split Jerk","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"One-Arm Kettlebell Split Snatch","m":["shoulders"],"e":"kettlebells","l":"expert","c":"strength"},
  {"n":"One-Arm Kettlebell Swings","m":["hamstrings"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"One-Arm Long Bar Row","m":["middle back"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"One-Arm Medicine Ball Slam","m":["abdominals"],"e":"medicine ball","l":"beginner","c":"strength"},
  {"n":"One-Arm Open Palm Kettlebell Clean","m":["hamstrings"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"One-Arm Overhead Kettlebell Squats","m":["quadriceps"],"e":"kettlebells","l":"expert","c":"strength"},
  {"n":"One-Arm Side Deadlift","m":["quadriceps"],"e":"barbell","l":"expert","c":"strength"},
  {"n":"One-Arm Side Laterals","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"One-Legged Cable Kickback","m":["glutes"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Open Palm Kettlebell Clean","m":["hamstrings"],"e":"kettlebells","l":"expert","c":"strength"},
  {"n":"Otis-Up","m":["abdominals"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Overhead Cable Curl","m":["biceps"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Overhead Lat","m":["lats"],"e":"other","l":"expert","c":"stretching"},
  {"n":"Overhead Slam","m":["lats"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Overhead Squat","m":["quadriceps"],"e":"barbell","l":"expert","c":"olympic weightlifting"},
  {"n":"Overhead Stretch","m":["abdominals"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Overhead Triceps","m":["triceps"],"e":"body only","l":"expert","c":"stretching"},
  {"n":"Pallof Press","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Pallof Press With Rotation","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Palms-Down Dumbbell Wrist Curl Over A Bench","m":["forearms"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Palms-Down Wrist Curl Over A Bench","m":["forearms"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Palms-Up Barbell Wrist Curl Over A Bench","m":["forearms"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Palms-Up Dumbbell Wrist Curl Over A Bench","m":["forearms"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Parallel Bar Dip","m":["triceps"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Pelvic Tilt Into Bridge","m":["lower back"],"e":null,"l":"intermediate","c":"stretching"},
  {"n":"Peroneals Stretch","m":["calves"],"e":"other","l":"intermediate","c":"stretching"},
  {"n":"Peroneals-SMR","m":["calves"],"e":"foam roll","l":"intermediate","c":"stretching"},
  {"n":"Physioball Hip Bridge","m":["glutes"],"e":"exercise ball","l":"beginner","c":"strength"},
  {"n":"Pin Presses","m":["triceps"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Piriformis-SMR","m":["glutes"],"e":"foam roll","l":"intermediate","c":"stretching"},
  {"n":"Plank","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Plate Pinch","m":["forearms"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Plate Twist","m":["abdominals"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Platform Hamstring Slides","m":["hamstrings"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Plie Dumbbell Squat","m":["quadriceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Plyo Kettlebell Pushups","m":["chest"],"e":"kettlebells","l":"expert","c":"strength"},
  {"n":"Plyo Push-up","m":["chest"],"e":"body only","l":"beginner","c":"plyometrics"},
  {"n":"Posterior Tibialis Stretch","m":["calves"],"e":"other","l":"intermediate","c":"stretching"},
  {"n":"Power Clean","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Power Clean from Blocks","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Power Jerk","m":["quadriceps"],"e":"barbell","l":"expert","c":"olympic weightlifting"},
  {"n":"Power Partials","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Power Snatch","m":["hamstrings"],"e":"barbell","l":"expert","c":"olympic weightlifting"},
  {"n":"Power Snatch from Blocks","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Power Stairs","m":["hamstrings"],"e":"other","l":"intermediate","c":"strongman"},
  {"n":"Preacher Curl","m":["biceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Preacher Hammer Dumbbell Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Press Sit-Up","m":["abdominals"],"e":"barbell","l":"expert","c":"strength"},
  {"n":"Prone Manual Hamstring","m":["hamstrings"],"e":null,"l":"beginner","c":"strength"},
  {"n":"Prowler Sprint","m":["hamstrings"],"e":"other","l":"beginner","c":"cardio"},
  {"n":"Pull Through","m":["glutes"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Pullups","m":["lats"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Push Press","m":["shoulders"],"e":"barbell","l":"expert","c":"olympic weightlifting"},
  {"n":"Push Press - Behind the Neck","m":["shoulders"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Push Up to Side Plank","m":["chest"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Push-Up Wide","m":["chest"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Push-Ups - Close Triceps Position","m":["triceps"],"e":"body only","l":"intermediate","c":"strength"},
  {"n":"Push-Ups With Feet Elevated","m":["chest"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Push-Ups With Feet On An Exercise Ball","m":["chest"],"e":"exercise ball","l":"intermediate","c":"strength"},
  {"n":"Pushups","m":["chest"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Pushups (Close and Wide Hand Positions)","m":["chest"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Pyramid","m":["lower back"],"e":"exercise ball","l":"beginner","c":"stretching"},
  {"n":"Quad Stretch","m":["quadriceps"],"e":"other","l":"intermediate","c":"stretching"},
  {"n":"Quadriceps-SMR","m":["quadriceps"],"e":"foam roll","l":"intermediate","c":"stretching"},
  {"n":"Quick Leap","m":["quadriceps"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Rack Delivery","m":["shoulders"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Rack Pull with Bands","m":["lower back"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Rack Pulls","m":["lower back"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Rear Leg Raises","m":["quadriceps"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Recumbent Bike","m":["quadriceps"],"e":"machine","l":"beginner","c":"cardio"},
  {"n":"Return Push from Stance","m":["shoulders"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Reverse Band Bench Press","m":["triceps"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Reverse Band Box Squat","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Reverse Band Deadlift","m":["lower back"],"e":"barbell","l":"expert","c":"powerlifting"},
  {"n":"Reverse Band Power Squat","m":["quadriceps"],"e":"barbell","l":"expert","c":"powerlifting"},
  {"n":"Reverse Band Sumo Deadlift","m":["hamstrings"],"e":"barbell","l":"expert","c":"powerlifting"},
  {"n":"Reverse Barbell Curl","m":["biceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Reverse Barbell Preacher Curls","m":["biceps"],"e":"e-z curl bar","l":"intermediate","c":"strength"},
  {"n":"Reverse Cable Curl","m":["biceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Reverse Crunch","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Reverse Flyes","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Reverse Flyes With External Rotation","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Reverse Grip Bent-Over Rows","m":["middle back"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Reverse Grip Triceps Pushdown","m":["triceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Reverse Hyperextension","m":["hamstrings"],"e":"machine","l":"intermediate","c":"strength"},
  {"n":"Reverse Machine Flyes","m":["shoulders"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Reverse Plate Curls","m":["biceps"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Reverse Triceps Bench Press","m":["triceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Rhomboids-SMR","m":["middle back"],"e":"foam roll","l":"intermediate","c":"stretching"},
  {"n":"Rickshaw Carry","m":["forearms"],"e":"other","l":"intermediate","c":"strongman"},
  {"n":"Rickshaw Deadlift","m":["quadriceps"],"e":"other","l":"intermediate","c":"strongman"},
  {"n":"Ring Dips","m":["triceps"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Rocket Jump","m":["quadriceps"],"e":"body only","l":"beginner","c":"plyometrics"},
  {"n":"Rocking Standing Calf Raise","m":["calves"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Rocky Pull-Ups/Pulldowns","m":["lats"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Romanian Deadlift","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Romanian Deadlift from Deficit","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Rope Climb","m":["lats"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Rope Crunch","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Rope Jumping","m":["quadriceps"],"e":"other","l":"intermediate","c":"cardio"},
  {"n":"Rope Straight-Arm Pulldown","m":["lats"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Round The World Shoulder Stretch","m":["shoulders"],"e":"other","l":"beginner","c":"stretching"},
  {"n":"Rowing, Stationary","m":["quadriceps"],"e":"machine","l":"intermediate","c":"cardio"},
  {"n":"Runner's Stretch","m":["hamstrings"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Running, Treadmill","m":["quadriceps"],"e":"machine","l":"beginner","c":"cardio"},
  {"n":"Russian Twist","m":["abdominals"],"e":"body only","l":"intermediate","c":"strength"},
  {"n":"Sandbag Load","m":["quadriceps"],"e":"other","l":"beginner","c":"strongman"},
  {"n":"Scapular Pull-Up","m":["traps"],"e":null,"l":"beginner","c":"strength"},
  {"n":"Scissor Kick","m":["abdominals"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Scissors Jump","m":["quadriceps"],"e":"body only","l":"beginner","c":"plyometrics"},
  {"n":"Seated Band Hamstring Curl","m":["hamstrings"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Seated Barbell Military Press","m":["shoulders"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Seated Barbell Twist","m":["abdominals"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Seated Bent-Over One-Arm Dumbbell Triceps Extension","m":["triceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Seated Bent-Over Rear Delt Raise","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Seated Bent-Over Two-Arm Dumbbell Triceps Extension","m":["triceps"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Seated Biceps","m":["biceps"],"e":"body only","l":"expert","c":"stretching"},
  {"n":"Seated Cable Rows","m":["middle back"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Seated Cable Shoulder Press","m":["shoulders"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Seated Calf Raise","m":["calves"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Seated Calf Stretch","m":["calves"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Seated Close-Grip Concentration Barbell Curl","m":["biceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Seated Dumbbell Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Seated Dumbbell Inner Biceps Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Seated Dumbbell Palms-Down Wrist Curl","m":["forearms"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Seated Dumbbell Palms-Up Wrist Curl","m":["forearms"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Seated Dumbbell Press","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Seated Flat Bench Leg Pull-In","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Seated Floor Hamstring Stretch","m":["hamstrings"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Seated Front Deltoid","m":["shoulders"],"e":"body only","l":"expert","c":"stretching"},
  {"n":"Seated Glute","m":["glutes"],"e":"body only","l":"expert","c":"stretching"},
  {"n":"Seated Good Mornings","m":["lower back"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Seated Hamstring","m":["hamstrings"],"e":null,"l":"expert","c":"stretching"},
  {"n":"Seated Hamstring and Calf Stretch","m":["hamstrings"],"e":"other","l":"intermediate","c":"stretching"},
  {"n":"Seated Head Harness Neck Resistance","m":["neck"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Seated Leg Curl","m":["hamstrings"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Seated Leg Tucks","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Seated One-arm Cable Pulley Rows","m":["middle back"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Seated One-Arm Dumbbell Palms-Down Wrist Curl","m":["forearms"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Seated One-Arm Dumbbell Palms-Up Wrist Curl","m":["forearms"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Seated Overhead Stretch","m":["abdominals"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Seated Palm-Up Barbell Wrist Curl","m":["forearms"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Seated Palms-Down Barbell Wrist Curl","m":["forearms"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Seated Side Lateral Raise","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Seated Triceps Press","m":["triceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Seated Two-Arm Palms-Up Low-Pulley Wrist Curl","m":["forearms"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"See-Saw Press (Alternating Side Press)","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Shotgun Row","m":["lats"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Shoulder Circles","m":["shoulders"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Shoulder Press - With Bands","m":["shoulders"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Shoulder Raise","m":["shoulders"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Shoulder Stretch","m":["shoulders"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Side Bridge","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Side Hop-Sprint","m":["quadriceps"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Side Jackknife","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Side Lateral Raise","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Side Laterals to Front Raise","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Side Leg Raises","m":["adductors"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Side Lying Groin Stretch","m":["adductors"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Side Neck Stretch","m":["neck"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Side Standing Long Jump","m":["quadriceps"],"e":null,"l":"beginner","c":"plyometrics"},
  {"n":"Side to Side Box Shuffle","m":["quadriceps"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Side To Side Chins","m":["lats"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Side Wrist Pull","m":["shoulders"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Side-Lying Floor Stretch","m":["lats"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Single Dumbbell Raise","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Single Leg Butt Kick","m":["quadriceps"],"e":"body only","l":"beginner","c":"plyometrics"},
  {"n":"Single Leg Glute Bridge","m":["glutes"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Single Leg Push-off","m":["quadriceps"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Single-Arm Cable Crossover","m":["chest"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Single-Arm Linear Jammer","m":["shoulders"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Single-Arm Push-Up","m":["chest"],"e":"body only","l":"intermediate","c":"strength"},
  {"n":"Single-Cone Sprint Drill","m":["quadriceps"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Single-Leg High Box Squat","m":["quadriceps"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Single-Leg Hop Progression","m":["quadriceps"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Single-Leg Lateral Hop","m":["quadriceps"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Single-Leg Leg Extension","m":["quadriceps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Single-Leg Stride Jump","m":["quadriceps"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Sit Squats","m":["quadriceps"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Sit-Up","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Skating","m":["quadriceps"],"e":"other","l":"intermediate","c":"cardio"},
  {"n":"Sled Drag - Harness","m":["quadriceps"],"e":"other","l":"beginner","c":"strongman"},
  {"n":"Sled Overhead Backward Walk","m":["shoulders"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Sled Overhead Triceps Extension","m":["triceps"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Sled Push","m":["quadriceps"],"e":"other","l":"beginner","c":"strongman"},
  {"n":"Sled Reverse Flye","m":["shoulders"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Sled Row","m":["middle back"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Sledgehammer Swings","m":["abdominals"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Smith Incline Shoulder Raise","m":["shoulders"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Smith Machine Behind the Back Shrug","m":["traps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Machine Bench Press","m":["chest"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Machine Bent Over Row","m":["middle back"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Machine Calf Raise","m":["calves"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Machine Close-Grip Bench Press","m":["triceps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Machine Decline Press","m":["chest"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Machine Hang Power Clean","m":["hamstrings"],"e":"machine","l":"intermediate","c":"strength"},
  {"n":"Smith Machine Hip Raise","m":["abdominals"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Machine Incline Bench Press","m":["chest"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Machine Leg Press","m":["quadriceps"],"e":"machine","l":"intermediate","c":"strength"},
  {"n":"Smith Machine One-Arm Upright Row","m":["shoulders"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Machine Overhead Shoulder Press","m":["shoulders"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Machine Pistol Squat","m":["quadriceps"],"e":"machine","l":"intermediate","c":"strength"},
  {"n":"Smith Machine Reverse Calf Raises","m":["calves"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Machine Squat","m":["quadriceps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Machine Stiff-Legged Deadlift","m":["hamstrings"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Machine Upright Row","m":["traps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Smith Single-Leg Split Squat","m":["quadriceps"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Snatch","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Snatch Balance","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Snatch Deadlift","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Snatch from Blocks","m":["quadriceps"],"e":"barbell","l":"expert","c":"olympic weightlifting"},
  {"n":"Snatch Pull","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Snatch Shrug","m":["traps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Speed Band Overhead Triceps","m":["triceps"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Speed Box Squat","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Speed Squats","m":["quadriceps"],"e":"barbell","l":"expert","c":"strength"},
  {"n":"Spell Caster","m":["abdominals"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Spider Crawl","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Spider Curl","m":["biceps"],"e":"e-z curl bar","l":"beginner","c":"strength"},
  {"n":"Spinal Stretch","m":["middle back"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Split Clean","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Split Jerk","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Split Jump","m":["quadriceps"],"e":"body only","l":"beginner","c":"plyometrics"},
  {"n":"Split Snatch","m":["hamstrings"],"e":"barbell","l":"expert","c":"olympic weightlifting"},
  {"n":"Split Squat with Dumbbells","m":["quadriceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Split Squats","m":["hamstrings"],"e":null,"l":"intermediate","c":"stretching"},
  {"n":"Squat Jerk","m":["quadriceps"],"e":"barbell","l":"expert","c":"strength"},
  {"n":"Squat with Bands","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Squat with Chains","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Squat with Plate Movers","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Squats - With Bands","m":["quadriceps"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Stairmaster","m":["quadriceps"],"e":"machine","l":"intermediate","c":"cardio"},
  {"n":"Standing Alternating Dumbbell Press","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Standing Barbell Calf Raise","m":["calves"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Standing Barbell Press Behind Neck","m":["shoulders"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Standing Bent-Over One-Arm Dumbbell Triceps Extension","m":["triceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Standing Bent-Over Two-Arm Dumbbell Triceps Extension","m":["triceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Standing Biceps Cable Curl","m":["biceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Standing Biceps Stretch","m":["biceps"],"e":"other","l":"beginner","c":"stretching"},
  {"n":"Standing Bradford Press","m":["shoulders"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Standing Cable Chest Press","m":["chest"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Standing Cable Lift","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Standing Cable Wood Chop","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Standing Calf Raises","m":["calves"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Standing Concentration Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Standing Dumbbell Calf Raise","m":["calves"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Standing Dumbbell Press","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Standing Dumbbell Reverse Curl","m":["biceps"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Standing Dumbbell Straight-Arm Front Delt Raise Above Head","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Standing Dumbbell Triceps Extension","m":["triceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Standing Dumbbell Upright Row","m":["traps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Standing Elevated Quad Stretch","m":["quadriceps"],"e":"other","l":"beginner","c":"stretching"},
  {"n":"Standing Front Barbell Raise Over Head","m":["shoulders"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Standing Gastrocnemius Calf Stretch","m":["calves"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Standing Hamstring and Calf Stretch","m":["hamstrings"],"e":"other","l":"beginner","c":"stretching"},
  {"n":"Standing Hip Circles","m":["abductors"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Standing Hip Flexors","m":["quadriceps"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Standing Inner-Biceps Curl","m":["biceps"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Standing Lateral Stretch","m":["abdominals"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Standing Leg Curl","m":["hamstrings"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Standing Long Jump","m":["quadriceps"],"e":"body only","l":"beginner","c":"plyometrics"},
  {"n":"Standing Low-Pulley Deltoid Raise","m":["shoulders"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Standing Low-Pulley One-Arm Triceps Extension","m":["triceps"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Standing Military Press","m":["shoulders"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Standing Olympic Plate Hand Squeeze","m":["forearms"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Standing One-Arm Cable Curl","m":["biceps"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Standing One-Arm Dumbbell Curl Over Incline Bench","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Standing One-Arm Dumbbell Triceps Extension","m":["triceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Standing Overhead Barbell Triceps Extension","m":["triceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Standing Palm-In One-Arm Dumbbell Press","m":["shoulders"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Standing Palms-In Dumbbell Press","m":["shoulders"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Standing Palms-Up Barbell Behind The Back Wrist Curl","m":["forearms"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Standing Pelvic Tilt","m":["lower back"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Standing Rope Crunch","m":["abdominals"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Standing Soleus And Achilles Stretch","m":["calves"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Standing Toe Touches","m":["hamstrings"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Standing Towel Triceps Extension","m":["triceps"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Standing Two-Arm Overhead Throw","m":["shoulders"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Star Jump","m":["quadriceps"],"e":"body only","l":"beginner","c":"plyometrics"},
  {"n":"Step Mill","m":["quadriceps"],"e":"machine","l":"intermediate","c":"cardio"},
  {"n":"Step-up with Knee Raise","m":["glutes"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Stiff Leg Barbell Good Morning","m":["lower back"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Stiff-Legged Barbell Deadlift","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Stiff-Legged Dumbbell Deadlift","m":["hamstrings"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Stomach Vacuum","m":["abdominals"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Straight Bar Bench Mid Rows","m":["middle back"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Straight Raises on Incline Bench","m":["shoulders"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Straight-Arm Dumbbell Pullover","m":["chest"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Straight-Arm Pulldown","m":["lats"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Stride Jump Crossover","m":["quadriceps"],"e":"other","l":"beginner","c":"plyometrics"},
  {"n":"Sumo Deadlift","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Sumo Deadlift with Bands","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Sumo Deadlift with Chains","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"powerlifting"},
  {"n":"Superman","m":["lower back"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Supine Chest Throw","m":["triceps"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Supine One-Arm Overhead Throw","m":["abdominals"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Supine Two-Arm Overhead Throw","m":["abdominals"],"e":"medicine ball","l":"beginner","c":"plyometrics"},
  {"n":"Suspended Fallout","m":["abdominals"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Suspended Push-Up","m":["chest"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Suspended Reverse Crunch","m":["abdominals"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Suspended Row","m":["middle back"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Suspended Split Squat","m":["quadriceps"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Svend Press","m":["chest"],"e":"other","l":"beginner","c":"strength"},
  {"n":"T-Bar Row with Handle","m":["middle back"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Tate Press","m":["triceps"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"The Straddle","m":["hamstrings"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Thigh Abductor","m":["abductors"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Thigh Adductor","m":["adductors"],"e":"machine","l":"beginner","c":"strength"},
  {"n":"Tire Flip","m":["quadriceps"],"e":"other","l":"intermediate","c":"strongman"},
  {"n":"Toe Touchers","m":["abdominals"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Torso Rotation","m":["abdominals"],"e":"exercise ball","l":"beginner","c":"stretching"},
  {"n":"Trail Running/Walking","m":["quadriceps"],"e":null,"l":"beginner","c":"cardio"},
  {"n":"Trap Bar Deadlift","m":["quadriceps"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Tricep Dumbbell Kickback","m":["triceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Tricep Side Stretch","m":["triceps"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Triceps Overhead Extension with Rope","m":["triceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Triceps Pushdown","m":["triceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Triceps Pushdown - Rope Attachment","m":["triceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Triceps Pushdown - V-Bar Attachment","m":["triceps"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Triceps Stretch","m":["triceps"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Tuck Crunch","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Two-Arm Dumbbell Preacher Curl","m":["biceps"],"e":"dumbbell","l":"beginner","c":"strength"},
  {"n":"Two-Arm Kettlebell Clean","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Two-Arm Kettlebell Jerk","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Two-Arm Kettlebell Military Press","m":["shoulders"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Two-Arm Kettlebell Row","m":["middle back"],"e":"kettlebells","l":"intermediate","c":"strength"},
  {"n":"Underhand Cable Pulldowns","m":["lats"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Upper Back Stretch","m":["middle back"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Upper Back-Leg Grab","m":["hamstrings"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"Upright Barbell Row","m":["shoulders"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Upright Cable Row","m":["traps"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Upright Row - With Bands","m":["traps"],"e":"bands","l":"beginner","c":"strength"},
  {"n":"Upward Stretch","m":["shoulders"],"e":null,"l":"beginner","c":"stretching"},
  {"n":"V-Bar Pulldown","m":["lats"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"V-Bar Pullup","m":["lats"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Vertical Swing","m":["hamstrings"],"e":"dumbbell","l":"beginner","c":"plyometrics"},
  {"n":"Walking, Treadmill","m":["quadriceps"],"e":"machine","l":"beginner","c":"cardio"},
  {"n":"Weighted Ball Hyperextension","m":["lower back"],"e":"exercise ball","l":"intermediate","c":"strength"},
  {"n":"Weighted Ball Side Bend","m":["abdominals"],"e":"exercise ball","l":"intermediate","c":"strength"},
  {"n":"Weighted Bench Dip","m":["triceps"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Weighted Crunches","m":["abdominals"],"e":"medicine ball","l":"beginner","c":"strength"},
  {"n":"Weighted Jump Squat","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Weighted Pull Ups","m":["lats"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Weighted Sissy Squat","m":["quadriceps"],"e":"barbell","l":"expert","c":"strength"},
  {"n":"Weighted Sit-Ups - With Bands","m":["abdominals"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Weighted Squat","m":["quadriceps"],"e":"other","l":"intermediate","c":"strength"},
  {"n":"Wide Stance Barbell Squat","m":["quadriceps"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Wide Stance Stiff Legs","m":["hamstrings"],"e":"barbell","l":"intermediate","c":"olympic weightlifting"},
  {"n":"Wide-Grip Barbell Bench Press","m":["chest"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Wide-Grip Decline Barbell Bench Press","m":["chest"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Wide-Grip Decline Barbell Pullover","m":["chest"],"e":"barbell","l":"intermediate","c":"strength"},
  {"n":"Wide-Grip Lat Pulldown","m":["lats"],"e":"cable","l":"beginner","c":"strength"},
  {"n":"Wide-Grip Pulldown Behind The Neck","m":["lats"],"e":"cable","l":"intermediate","c":"strength"},
  {"n":"Wide-Grip Rear Pull-Up","m":["lats"],"e":"body only","l":"intermediate","c":"strength"},
  {"n":"Wide-Grip Standing Barbell Curl","m":["biceps"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Wind Sprints","m":["abdominals"],"e":"body only","l":"beginner","c":"strength"},
  {"n":"Windmills","m":["abductors"],"e":null,"l":"intermediate","c":"stretching"},
  {"n":"World's Greatest Stretch","m":["hamstrings"],"e":null,"l":"intermediate","c":"stretching"},
  {"n":"Wrist Circles","m":["forearms"],"e":"body only","l":"beginner","c":"stretching"},
  {"n":"Wrist Roller","m":["forearms"],"e":"other","l":"beginner","c":"strength"},
  {"n":"Wrist Rotations with Straight Bar","m":["forearms"],"e":"barbell","l":"beginner","c":"strength"},
  {"n":"Yoke Walk","m":["quadriceps"],"e":"other","l":"intermediate","c":"strongman"},
  {"n":"Zercher Squats","m":["quadriceps"],"e":"barbell","l":"expert","c":"strength"},
  {"n":"Zottman Curl","m":["biceps"],"e":"dumbbell","l":"intermediate","c":"strength"},
  {"n":"Zottman Preacher Curl","m":["biceps"],"e":"dumbbell","l":"intermediate","c":"strength"}
];
